import { LocalizedText, makeText } from './i18n';
import { GRAMMAR_ITEMS } from './grammarData';

export type StudyKind = 'hiragana' | 'katakana' | 'vocab' | 'line' | 'grammar';
export type JlptLevel = 'N5' | 'N4' | 'N3' | 'N2' | 'N1';

export const JLPT_LEVELS: JlptLevel[] = ['N5', 'N4', 'N3', 'N2', 'N1'];

export type StudyItem = {
  id: string;
  kind: StudyKind;
  level: JlptLevel;
  display: string;
  kana: string;
  romaji: string;
  meaning: LocalizedText;
  topic: LocalizedText;
  grammar?: {
    answer: string;
    completedSentence: string;
    options: string[];
  };
};

const topic = {
  hiragana: text('Hiragana', '平假名', 'ひらがな', '히라가나'),
  katakana: text('Katakana', '片假名', 'カタカナ', '가타카나'),
  greetings: text('Greetings', '问候', 'あいさつ', '인사'),
  school: text('School', '校园', '学校', '학교'),
  daily: text('Daily life', '生活', '生活', '생활'),
  food: text('Food', '饮食', '食べ物', '음식'),
  travel: text('Travel', '出行', '移動', '이동'),
  time: text('Time', '时间', '時間', '시간'),
  family: text('Family', '家庭', '家族', '가족'),
  people: text('People', '人物', '人', '사람'),
  place: text('Places', '地点', '場所', '장소'),
  object: text('Objects', '物品', '物', '물건'),
  nature: text('Nature', '自然', '自然', '자연'),
  number: text('Numbers', '数字', '数字', '숫자'),
  question: text('Question words', '疑问词', '疑問詞', '의문사'),
  feeling: text('Feelings', '感觉', '気持ち', '감정'),
  adjective: text('Descriptions', '形容', '形容', '묘사'),
  verb: text('Actions', '动词', '動詞', '동사'),
  plans: text('Plans', '计划', '予定', '계획'),
  growth: text('Growth', '成长', '成長', '성장'),
  society: text('Society', '社会', '社会', '사회'),
  abstract: text('Abstract thought', '抽象思考', '抽象的な考え', '추상적 사고'),
  nuance: text('Nuance', '语感', 'ニュアンス', '뉘앙스'),
  courage: text('Courage line', '热血台词', '熱いセリフ', '열혈 대사'),
  friendship: text('Friendship line', '友情台词', '友情セリフ', '우정 대사'),
  adventure: text('Adventure line', '冒险台词', '冒険セリフ', '모험 대사'),
  schoolLine: text('School line', '校园台词', '学園セリフ', '학교 대사'),
  mystery: text('Mystery line', '悬疑台词', '謎のセリフ', '미스터리 대사'),
};

const kanaRows = [
  ['あ', 'ア', 'a'],
  ['い', 'イ', 'i'],
  ['う', 'ウ', 'u'],
  ['え', 'エ', 'e'],
  ['お', 'オ', 'o'],
  ['か', 'カ', 'ka'],
  ['き', 'キ', 'ki'],
  ['く', 'ク', 'ku'],
  ['け', 'ケ', 'ke'],
  ['こ', 'コ', 'ko'],
  ['さ', 'サ', 'sa'],
  ['し', 'シ', 'shi'],
  ['す', 'ス', 'su'],
  ['せ', 'セ', 'se'],
  ['そ', 'ソ', 'so'],
  ['た', 'タ', 'ta'],
  ['ち', 'チ', 'chi'],
  ['つ', 'ツ', 'tsu'],
  ['て', 'テ', 'te'],
  ['と', 'ト', 'to'],
  ['な', 'ナ', 'na'],
  ['に', 'ニ', 'ni'],
  ['ぬ', 'ヌ', 'nu'],
  ['ね', 'ネ', 'ne'],
  ['の', 'ノ', 'no'],
  ['は', 'ハ', 'ha'],
  ['ひ', 'ヒ', 'hi'],
  ['ふ', 'フ', 'fu'],
  ['へ', 'ヘ', 'he'],
  ['ほ', 'ホ', 'ho'],
  ['ま', 'マ', 'ma'],
  ['み', 'ミ', 'mi'],
  ['む', 'ム', 'mu'],
  ['め', 'メ', 'me'],
  ['も', 'モ', 'mo'],
  ['や', 'ヤ', 'ya'],
  ['ゆ', 'ユ', 'yu'],
  ['よ', 'ヨ', 'yo'],
  ['ら', 'ラ', 'ra'],
  ['り', 'リ', 'ri'],
  ['る', 'ル', 'ru'],
  ['れ', 'レ', 're'],
  ['ろ', 'ロ', 'ro'],
  ['わ', 'ワ', 'wa'],
  ['を', 'ヲ', 'wo'],
  ['ん', 'ン', 'n'],
] as const;

export const HIRAGANA_ITEMS: StudyItem[] = kanaRows.map(([hiragana, , romaji]) => ({
  id: `hiragana-${romaji}`,
  kind: 'hiragana',
  level: 'N5',
  display: hiragana,
  kana: hiragana,
  romaji,
  meaning: text(`Hiragana ${romaji}`, `平假名 ${romaji}`, `ひらがな ${romaji}`, `히라가나 ${romaji}`),
  topic: topic.hiragana,
}));

export const KATAKANA_ITEMS: StudyItem[] = kanaRows.map(([, katakana, romaji]) => ({
  id: `katakana-${romaji}`,
  kind: 'katakana',
  level: 'N5',
  display: katakana,
  kana: katakana,
  romaji,
  meaning: text(`Katakana ${romaji}`, `片假名 ${romaji}`, `カタカナ ${romaji}`, `가타카나 ${romaji}`),
  topic: topic.katakana,
}));

export const VOCAB_ITEMS: StudyItem[] = [
  vocab('ohayou', 'おはよう', 'おはよう', 'ohayou', text('Good morning', '早上好', '朝のあいさつ', '좋은 아침'), topic.greetings),
  vocab('konnichiwa', 'こんにちは', 'こんにちは', 'konnichiwa', text('Hello', '你好', '昼のあいさつ', '안녕하세요'), topic.greetings),
  vocab('arigatou', 'ありがとう', 'ありがとう', 'arigatou', text('Thank you', '谢谢', '感謝', '고마워요'), topic.greetings),
  vocab('sumimasen', 'すみません', 'すみません', 'sumimasen', text('Excuse me', '不好意思', 'すみません', '실례합니다'), topic.greetings),
  vocab('sensei', '先生', 'せんせい', 'sensei', text('Teacher', '老师', '先生', '선생님'), topic.school),
  vocab('gakkou', '学校', 'がっこう', 'gakkou', text('School', '学校', '学校', '학교'), topic.school),
  vocab('benkyou', '勉強', 'べんきょう', 'benkyou', text('Study', '学习', '勉強', '공부'), topic.school),
  vocab('hon', '本', 'ほん', 'hon', text('Book', '书', '本', '책'), topic.school),
  vocab('nihongo', '日本語', 'にほんご', 'nihongo', text('Japanese language', '日语', '日本語', '일본어'), topic.school),
  vocab('tomodachi', '友達', 'ともだち', 'tomodachi', text('Friend', '朋友', '友達', '친구'), topic.daily),
  vocab('watashi', '私', 'わたし', 'watashi', text('I / me', '我', '私', '나'), topic.daily),
  vocab('anata', 'あなた', 'あなた', 'anata', text('You', '你', 'あなた', '당신'), topic.daily),
  vocab('ie', '家', 'いえ', 'ie', text('Home / house', '家', '家', '집'), topic.daily),
  vocab('mizu', '水', 'みず', 'mizu', text('Water', '水', '水', '물'), topic.food),
  vocab('ocha', 'お茶', 'おちゃ', 'ocha', text('Tea', '茶', 'お茶', '차'), topic.food),
  vocab('gohan', 'ご飯', 'ごはん', 'gohan', text('Rice / meal', '米饭', 'ご飯', '밥'), topic.food),
  vocab('pan', 'パン', 'パン', 'pan', text('Bread', '面包', 'パン', '빵'), topic.food),
  vocab('sakana', '魚', 'さかな', 'sakana', text('Fish', '鱼', '魚', '생선'), topic.food),
  vocab('eki', '駅', 'えき', 'eki', text('Station', '车站', '駅', '역'), topic.travel),
  vocab('densha', '電車', 'でんしゃ', 'densha', text('Train', '电车', '電車', '전철'), topic.travel),
  vocab('basutei', 'バス停', 'バスてい', 'basutei', text('Bus stop', '公交站', 'バス停', '버스 정류장'), topic.travel),
  vocab('kippu', '切符', 'きっぷ', 'kippu', text('Ticket', '车票', '切符', '표'), topic.travel),
  vocab('michi', '道', 'みち', 'michi', text('Road / path', '道路', '道', '길'), topic.travel),
  vocab('asa', '朝', 'あさ', 'asa', text('Morning', '早晨', '朝', '아침'), topic.time),
  vocab('hiru', '昼', 'ひる', 'hiru', text('Noon / daytime', '中午', '昼', '낮'), topic.time),
  vocab('yoru', '夜', 'よる', 'yoru', text('Night', '夜晚', '夜', '밤'), topic.time),
  vocab('kyou', '今日', 'きょう', 'kyou', text('Today', '今天', '今日', '오늘'), topic.time),
  vocab('ashita', '明日', 'あした', 'ashita', text('Tomorrow', '明天', '明日', '내일'), topic.time),
  vocab('haha', '母', 'はは', 'haha', text('Mother', '母亲', '母', '어머니'), topic.family),
  vocab('chichi', '父', 'ちち', 'chichi', text('Father', '父亲', '父', '아버지'), topic.family),
  vocab('ani', '兄', 'あに', 'ani', text('Older brother', '哥哥', '兄', '형/오빠'), topic.family),
  vocab('ane', '姉', 'あね', 'ane', text('Older sister', '姐姐', '姉', '누나/언니'), topic.family),
  vocab('otouto', '弟', 'おとうと', 'otouto', text('Younger brother', '弟弟', '弟', '남동생'), topic.family),
  vocab('kazoku', '家族', 'かぞく', 'kazoku', text('Family', '家人', '家族', '가족'), topic.family),
  vocab('hito', '人', 'ひと', 'hito', text('Person', '人', '人', '사람'), topic.people),
  vocab('kodomo', '子供', 'こども', 'kodomo', text('Child', '孩子', '子供', '아이'), topic.people),
  vocab('onna-no-hito', '女の人', 'おんなのひと', 'onna no hito', text('Woman', '女性', '女の人', '여자'), topic.people),
  vocab('otoko-no-hito', '男の人', 'おとこのひと', 'otoko no hito', text('Man', '男性', '男の人', '남자'), topic.people),
  vocab('minna', '皆', 'みんな', 'minna', text('Everyone', '大家', '皆', '모두'), topic.people),
  vocab('namae', '名前', 'なまえ', 'namae', text('Name', '名字', '名前', '이름'), topic.people),
  vocab('kyoushitsu', '教室', 'きょうしつ', 'kyoushitsu', text('Classroom', '教室', '教室', '교실'), topic.place),
  vocab('toshokan', '図書館', 'としょかん', 'toshokan', text('Library', '图书馆', '図書館', '도서관'), topic.place),
  vocab('byouin', '病院', 'びょういん', 'byouin', text('Hospital', '医院', '病院', '병원'), topic.place),
  vocab('mise', '店', 'みせ', 'mise', text('Shop', '商店', '店', '가게'), topic.place),
  vocab('kouen', '公園', 'こうえん', 'kouen', text('Park', '公园', '公園', '공원'), topic.place),
  vocab('machi', '町', 'まち', 'machi', text('Town', '城镇', '町', '마을'), topic.place),
  vocab('kaban', '鞄', 'かばん', 'kaban', text('Bag', '包', '鞄', '가방'), topic.object),
  vocab('denwa', '電話', 'でんわ', 'denwa', text('Phone', '电话', '電話', '전화'), topic.object),
  vocab('tsukue', '机', 'つくえ', 'tsukue', text('Desk', '桌子', '机', '책상'), topic.object),
  vocab('isu', '椅子', 'いす', 'isu', text('Chair', '椅子', '椅子', '의자'), topic.object),
  vocab('kasa', '傘', 'かさ', 'kasa', text('Umbrella', '伞', '傘', '우산'), topic.object),
  vocab('kutsu', '靴', 'くつ', 'kutsu', text('Shoes', '鞋', '靴', '신발'), topic.object),
  vocab('ame', '雨', 'あめ', 'ame', text('Rain', '雨', '雨', '비'), topic.nature),
  vocab('yuki', '雪', 'ゆき', 'yuki', text('Snow', '雪', '雪', '눈'), topic.nature),
  vocab('kaze', '風', 'かぜ', 'kaze', text('Wind', '风', '風', '바람'), topic.nature),
  vocab('sora', '空', 'そら', 'sora', text('Sky', '天空', '空', '하늘'), topic.nature),
  vocab('hana', '花', 'はな', 'hana', text('Flower', '花', '花', '꽃'), topic.nature),
  vocab('ki', '木', 'き', 'ki', text('Tree', '树', '木', '나무'), topic.nature),
  vocab('umi', '海', 'うみ', 'umi', text('Sea', '海', '海', '바다'), topic.nature),
  vocab('yama', '山', 'やま', 'yama', text('Mountain', '山', '山', '산'), topic.nature),
  vocab('hitotsu', '一つ', 'ひとつ', 'hitotsu', text('One thing', '一个', '一つ', '하나'), topic.number),
  vocab('futatsu', '二つ', 'ふたつ', 'futatsu', text('Two things', '两个', '二つ', '둘'), topic.number),
  vocab('mittsu', '三つ', 'みっつ', 'mittsu', text('Three things', '三个', '三つ', '셋'), topic.number),
  vocab('yottsu', '四つ', 'よっつ', 'yottsu', text('Four things', '四个', '四つ', '넷'), topic.number),
  vocab('itsutsu', '五つ', 'いつつ', 'itsutsu', text('Five things', '五个', '五つ', '다섯'), topic.number),
  vocab('ichiban', '一番', 'いちばん', 'ichiban', text('Number one / best', '第一/最好', '一番', '첫째/최고'), topic.number),
  vocab('nani', '何', 'なに', 'nani', text('What', '什么', '何', '무엇'), topic.question),
  vocab('doko', 'どこ', 'どこ', 'doko', text('Where', '哪里', 'どこ', '어디'), topic.question),
  vocab('itsu', 'いつ', 'いつ', 'itsu', text('When', '什么时候', 'いつ', '언제'), topic.question),
  vocab('dare', '誰', 'だれ', 'dare', text('Who', '谁', '誰', '누구'), topic.question),
  vocab('doushite', 'どうして', 'どうして', 'doushite', text('Why', '为什么', 'どうして', '왜'), topic.question),
  vocab('douyatte', 'どうやって', 'どうやって', 'douyatte', text('How', '怎么做', 'どうやって', '어떻게'), topic.question),
  vocab('atsui', '暑い', 'あつい', 'atsui', text('Hot', '热', '暑い', '덥다'), topic.feeling),
  vocab('samui', '寒い', 'さむい', 'samui', text('Cold', '冷', '寒い', '춥다'), topic.feeling),
  vocab('tanoshii', '楽しい', 'たのしい', 'tanoshii', text('Fun', '开心', '楽しい', '즐겁다'), topic.feeling),
  vocab('muzukashii', '難しい', 'むずかしい', 'muzukashii', text('Difficult', '难', '難しい', '어렵다'), topic.feeling),
  vocab('yasashii', '易しい', 'やさしい', 'yasashii', text('Easy', '简单', '易しい', '쉽다'), topic.feeling),
  vocab('ookii', '大きい', 'おおきい', 'ookii', text('Big', '大的', '大きい', '크다'), topic.adjective),
  vocab('chiisai', '小さい', 'ちいさい', 'chiisai', text('Small', '小的', '小さい', '작다'), topic.adjective),
  vocab('hayai', '早い', 'はやい', 'hayai', text('Early / fast', '早的', '早い', '빠르다'), topic.adjective),
  vocab('osoi', '遅い', 'おそい', 'osoi', text('Late / slow', '晚的', '遅い', '늦다'), topic.adjective),
  vocab('iku', '行く', 'いく', 'iku', text('Go', '去', '行く', '가다'), topic.verb),
  vocab('kuru', '来る', 'くる', 'kuru', text('Come', '来', '来る', '오다'), topic.verb),
  vocab('miru', '見る', 'みる', 'miru', text('See / watch', '看', '見る', '보다'), topic.verb),
  vocab('kiku', '聞く', 'きく', 'kiku', text('Listen / ask', '听/问', '聞く', '듣다/묻다'), topic.verb),
  vocab('yomu', '読む', 'よむ', 'yomu', text('Read', '读', '読む', '읽다'), topic.verb),
  vocab('kaku', '書く', 'かく', 'kaku', text('Write', '写', '書く', '쓰다'), topic.verb),
  vocab('taberu', '食べる', 'たべる', 'taberu', text('Eat', '吃', '食べる', '먹다'), topic.verb),
  vocab('nomu', '飲む', 'のむ', 'nomu', text('Drink', '喝', '飲む', '마시다'), topic.verb),
  vocab('kau', '買う', 'かう', 'kau', text('Buy', '买', '買う', '사다'), topic.verb),
  vocab('hanasu', '話す', 'はなす', 'hanasu', text('Speak', '说', '話す', '말하다'), topic.verb),
  vocab('matsu', '待つ', 'まつ', 'matsu', text('Wait', '等待', '待つ', '기다리다'), topic.verb),
  vocab('tatsu', '立つ', 'たつ', 'tatsu', text('Stand', '站立', '立つ', '서다'), topic.verb),
  vocab('suwaru', '座る', 'すわる', 'suwaru', text('Sit', '坐', '座る', '앉다'), topic.verb),
  vocab('akeru', '開ける', 'あける', 'akeru', text('Open', '打开', '開ける', '열다'), topic.verb),
  vocab('shimeru', '閉める', 'しめる', 'shimeru', text('Close', '关闭', '閉める', '닫다'), topic.verb),
  vocab('tetsudau', '手伝う', 'てつだう', 'tetsudau', text('Help', '帮忙', '手伝う', '돕다'), topic.verb),
  vocab('omou', '思う', 'おもう', 'omou', text('Think', '想/认为', '思う', '생각하다'), topic.verb),
  vocab('shiru', '知る', 'しる', 'shiru', text('Know', '知道', '知る', '알다'), topic.verb),
  vocab('tsukuru', '作る', 'つくる', 'tsukuru', text('Make', '制作', '作る', '만들다'), topic.verb),
  vocab('tsukau', '使う', 'つかう', 'tsukau', text('Use', '使用', '使う', '사용하다'), topic.verb),
  vocab('yasumu', '休む', 'やすむ', 'yasumu', text('Rest', '休息', '休む', '쉬다'), topic.verb),
  vocab('neru', '寝る', 'ねる', 'neru', text('Sleep', '睡觉', '寝る', '자다'), topic.verb),
  vocab('hitsuyou', '必要', 'ひつよう', 'hitsuyou', text('Necessary', '必要', '必要', '필요함'), topic.plans, 'N4'),
  vocab('yotei', '予定', 'よてい', 'yotei', text('Plan / schedule', '计划/日程', '予定', '예정'), topic.plans, 'N4'),
  vocab('keiken', '経験', 'けいけん', 'keiken', text('Experience', '经验', '経験', '경험'), topic.growth, 'N4'),
  vocab('iken', '意見', 'いけん', 'iken', text('Opinion', '意见', '意見', '의견'), topic.daily, 'N4'),
  vocab('setsumei', '説明', 'せつめい', 'setsumei', text('Explanation', '说明', '説明', '설명'), topic.school, 'N4'),
  vocab('yakusoku', '約束', 'やくそく', 'yakusoku', text('Promise', '约定', '約束', '약속'), topic.friendship, 'N4'),
  vocab('junbi', '準備', 'じゅんび', 'junbi', text('Preparation', '准备', '準備', '준비'), topic.plans, 'N4'),
  vocab('renraku', '連絡', 'れんらく', 'renraku', text('Contact / message', '联系/消息', '連絡', '연락'), topic.daily, 'N4'),
  vocab('anzen', '安全', 'あんぜん', 'anzen', text('Safety', '安全', '安全', '안전'), topic.daily, 'N4'),
  vocab('zannen', '残念', 'ざんねん', 'zannen', text('Regrettable', '遗憾', '残念', '아쉬움'), topic.feeling, 'N4'),
  vocab('kaeru-change', '変える', 'かえる', 'kaeru', text('Change something', '改变某物', '変える', '바꾸다'), topic.verb, 'N4'),
  vocab('kimeru', '決める', 'きめる', 'kimeru', text('Decide', '决定', '決める', '정하다'), topic.verb, 'N4'),
  vocab('tsuzukeru', '続ける', 'つづける', 'tsuzukeru', text('Continue', '继续', '続ける', '계속하다'), topic.verb, 'N4'),
  vocab('erabu', '選ぶ', 'えらぶ', 'erabu', text('Choose', '选择', '選ぶ', '고르다'), topic.verb, 'N4'),
  vocab('shiraberu', '調べる', 'しらべる', 'shiraberu', text('Look up / investigate', '查询/调查', '調べる', '찾아보다/조사하다'), topic.verb, 'N4'),
  vocab('todokeru', '届ける', 'とどける', 'todokeru', text('Deliver', '送达', '届ける', '전달하다'), topic.verb, 'N4'),
  vocab('shoukai', '紹介', 'しょうかい', 'shoukai', text('Introduction', '介绍', '紹介', '소개'), topic.people, 'N4'),
  vocab('shoutai', '招待', 'しょうたい', 'shoutai', text('Invitation', '邀请', '招待', '초대'), topic.friendship, 'N4'),
  vocab('yoyaku', '予約', 'よやく', 'yoyaku', text('Reservation', '预约', '予約', '예약'), topic.plans, 'N4'),
  vocab('kaigi', '会議', 'かいぎ', 'kaigi', text('Meeting', '会议', '会議', '회의'), topic.society, 'N4'),
  vocab('kisoku', '規則', 'きそく', 'kisoku', text('Rule', '规则', '規則', '규칙'), topic.school, 'N4'),
  vocab('kimochi', '気持ち', 'きもち', 'kimochi', text('Feeling / mood', '心情/感受', '気持ち', '기분/마음'), topic.feeling, 'N4'),
  vocab('oboeru', '覚える', 'おぼえる', 'oboeru', text('Remember / memorize', '记住/背会', '覚える', '외우다/기억하다'), topic.verb, 'N4'),
  vocab('hajimeru', '始める', 'はじめる', 'hajimeru', text('Start something', '开始某事', '始める', '시작하다'), topic.verb, 'N4'),
  vocab('taisetsu', '大切', 'たいせつ', 'taisetsu', text('Important', '重要', '大切', '중요함'), topic.feeling, 'N4'),
  vocab('tokubetsu', '特別', 'とくべつ', 'tokubetsu', text('Special', '特别', '特別', '특별함'), topic.feeling, 'N4'),
  vocab('shinpai', '心配', 'しんぱい', 'shinpai', text('Worry', '担心', '心配', '걱정'), topic.feeling, 'N4'),
  vocab('annai', '案内', 'あんない', 'annai', text('Guidance', '引导/介绍', '案内', '안내'), topic.travel, 'N4'),
  vocab('kankou', '観光', 'かんこう', 'kankou', text('Sightseeing', '观光', '観光', '관광'), topic.travel, 'N4'),
  vocab('henji', '返事', 'へんじ', 'henji', text('Reply', '回复', '返事', '답장'), topic.daily, 'N4'),
  vocab('shitsumon', '質問', 'しつもん', 'shitsumon', text('Question', '问题/提问', '質問', '질문'), topic.question, 'N4'),
  vocab('mondai', '問題', 'もんだい', 'mondai', text('Problem', '问题', '問題', '문제'), topic.school, 'N4'),
  vocab('jugyou', '授業', 'じゅぎょう', 'jugyou', text('Lesson', '课程', '授業', '수업'), topic.school, 'N4'),
  vocab('tsutaeru', '伝える', 'つたえる', 'tsutaeru', text('Convey', '传达', '伝える', '전하다'), topic.verb, 'N4'),
  vocab('okureru', '遅れる', 'おくれる', 'okureru', text('Be late', '迟到/延迟', '遅れる', '늦다'), topic.time, 'N4'),
  vocab('maniau', '間に合う', 'まにあう', 'maniau', text('Be in time', '赶得上', '間に合う', '시간에 맞다'), topic.time, 'N4'),
  vocab('kanarazu', '必ず', 'かならず', 'kanarazu', text('Surely', '一定', '必ず', '반드시'), topic.plans, 'N4'),
  vocab('tokidoki', '時々', 'ときどき', 'tokidoki', text('Sometimes', '有时', '時々', '가끔'), topic.time, 'N4'),
  vocab('sugu', 'すぐ', 'すぐ', 'sugu', text('Immediately', '马上', 'すぐ', '바로'), topic.time, 'N4'),
  vocab('teinei', '丁寧', 'ていねい', 'teinei', text('Polite / careful', '礼貌/细致', '丁寧', '정중함/꼼꼼함'), topic.nuance, 'N4'),
  vocab('ryouri', '料理', 'りょうり', 'ryouri', text('Cooking / cuisine', '料理/菜肴', '料理', '요리'), topic.food, 'N4'),
  vocab('shumi', '趣味', 'しゅみ', 'shumi', text('Hobby', '兴趣爱好', '趣味', '취미'), topic.daily, 'N4'),
  vocab('byouki', '病気', 'びょうき', 'byouki', text('Illness', '生病/疾病', '病気', '병'), topic.feeling, 'N4'),
  vocab('shiken', '試験', 'しけん', 'shiken', text('Exam', '考试', '試験', '시험'), topic.school, 'N4'),
  vocab('goukaku', '合格', 'ごうかく', 'goukaku', text('Passing an exam', '考试合格', '合格', '합격'), topic.school, 'N4'),
  vocab('futsuu', '普通', 'ふつう', 'futsuu', text('Normal / ordinary', '普通/平常', '普通', '보통'), topic.daily, 'N4'),
  vocab('jiyuu', '自由', 'じゆう', 'jiyuu', text('Freedom', '自由', '自由', '자유'), topic.feeling, 'N4'),
  vocab('kiken', '危険', 'きけん', 'kiken', text('Danger', '危险', '危険', '위험'), topic.daily, 'N4'),
  vocab('kantan', '簡単', 'かんたん', 'kantan', text('Simple / easy', '简单', '簡単', '간단함'), topic.adjective, 'N4'),
  vocab('kibishii', '厳しい', 'きびしい', 'kibishii', text('Strict / harsh', '严格/严厉', '厳しい', '엄격함'), topic.adjective, 'N4'),
  vocab('tasukeru', '助ける', 'たすける', 'tasukeru', text('Help / rescue', '帮助/救助', '助ける', '돕다/구하다'), topic.verb, 'N4'),
  vocab('sagasu', '探す', 'さがす', 'sagasu', text('Search for', '寻找', '探す', '찾다'), topic.verb, 'N4'),
  vocab('naosu', '直す', 'なおす', 'naosu', text('Fix / correct', '修理/改正', '直す', '고치다'), topic.verb, 'N4'),
  vocab('naoru', '直る', 'なおる', 'naoru', text('Be fixed / recover', '修好/恢复', '直る', '고쳐지다/낫다'), topic.verb, 'N4'),
  vocab('ugoku', '動く', 'うごく', 'ugoku', text('Move', '移动/运转', '動く', '움직이다'), topic.verb, 'N4'),
  vocab('hairu', '入る', 'はいる', 'hairu', text('Enter', '进入', '入る', '들어가다'), topic.verb, 'N4'),
  vocab('deru', '出る', 'でる', 'deru', text('Leave / go out', '出去/出现', '出る', '나가다/나오다'), topic.verb, 'N4'),
  vocab('okuru', '送る', 'おくる', 'okuru', text('Send', '发送/送别', '送る', '보내다'), topic.verb, 'N4'),
  vocab('warau', '笑う', 'わらう', 'warau', text('Laugh / smile', '笑', '笑う', '웃다'), topic.feeling, 'N4'),
  vocab('naku', '泣く', 'なく', 'naku', text('Cry', '哭', '泣く', '울다'), topic.feeling, 'N4'),
  vocab('kanou', '可能', 'かのう', 'kanou', text('Possible', '可能', '可能', '가능함'), topic.abstract, 'N3'),
  vocab('shippai', '失敗', 'しっぱい', 'shippai', text('Failure', '失败', '失敗', '실패'), topic.growth, 'N3'),
  vocab('seikou', '成功', 'せいこう', 'seikou', text('Success', '成功', '成功', '성공'), topic.growth, 'N3'),
  vocab('mokuteki', '目的', 'もくてき', 'mokuteki', text('Purpose', '目的', '目的', '목적'), topic.abstract, 'N3'),
  vocab('jouken', '条件', 'じょうけん', 'jouken', text('Condition', '条件', '条件', '조건'), topic.abstract, 'N3'),
  vocab('kakunin', '確認', 'かくにん', 'kakunin', text('Confirmation', '确认', '確認', '확인'), topic.daily, 'N3'),
  vocab('kitai', '期待', 'きたい', 'kitai', text('Expectation', '期待', '期待', '기대'), topic.feeling, 'N3'),
  vocab('doryoku', '努力', 'どりょく', 'doryoku', text('Effort', '努力', '努力', '노력'), topic.growth, 'N3'),
  vocab('riyuu', '理由', 'りゆう', 'riyuu', text('Reason', '理由', '理由', '이유'), topic.abstract, 'N3'),
  vocab('bunka', '文化', 'ぶんか', 'bunka', text('Culture', '文化', '文化', '문화'), topic.society, 'N3'),
  vocab('shakai', '社会', 'しゃかい', 'shakai', text('Society', '社会', '社会', '사회'), topic.society, 'N3'),
  vocab('kankei', '関係', 'かんけい', 'kankei', text('Relationship', '关系', '関係', '관계'), topic.society, 'N3'),
  vocab('kuraberu', '比べる', 'くらべる', 'kuraberu', text('Compare', '比较', '比べる', '비교하다'), topic.verb, 'N3'),
  vocab('fueru', '増える', 'ふえる', 'fueru', text('Increase', '增加', '増える', '늘다'), topic.verb, 'N3'),
  vocab('heru', '減る', 'へる', 'heru', text('Decrease', '减少', '減る', '줄다'), topic.verb, 'N3'),
  vocab('nareru', '慣れる', 'なれる', 'nareru', text('Get used to', '习惯', '慣れる', '익숙해지다'), topic.verb, 'N3'),
  vocab('kekka', '結果', 'けっか', 'kekka', text('Result', '结果', '結果', '결과'), topic.growth, 'N3'),
  vocab('genin', '原因', 'げんいん', 'genin', text('Cause', '原因', '原因', '원인'), topic.abstract, 'N3'),
  vocab('kikai', '機会', 'きかい', 'kikai', text('Opportunity', '机会', '機会', '기회'), topic.plans, 'N3'),
  vocab('koudou', '行動', 'こうどう', 'koudou', text('Action / behavior', '行动/行为', '行動', '행동'), topic.verb, 'N3'),
  vocab('kankyou', '環境', 'かんきょう', 'kankyou', text('Environment', '环境', '環境', '환경'), topic.society, 'N3'),
  vocab('seichou', '成長', 'せいちょう', 'seichou', text('Personal growth', '成长', '成長', '성장'), topic.growth, 'N3'),
  vocab('setsuzoku', '接続', 'せつぞく', 'setsuzoku', text('Connection', '连接', '接続', '연결'), topic.abstract, 'N3'),
  vocab('kaiketsu', '解決', 'かいけつ', 'kaiketsu', text('Solution / resolution', '解决', '解決', '해결'), topic.abstract, 'N3'),
  vocab('kibou', '希望', 'きぼう', 'kibou', text('Hope', '希望', '希望', '희망'), topic.feeling, 'N3'),
  vocab('yuuki', '勇気', 'ゆうき', 'yuuki', text('Courage', '勇气', '勇気', '용기'), topic.courage, 'N3'),
  vocab('shunkan', '瞬間', 'しゅんかん', 'shunkan', text('Moment', '瞬间', '瞬間', '순간'), topic.time, 'N3'),
  vocab('gijutsu', '技術', 'ぎじゅつ', 'gijutsu', text('Technology / skill', '技术/技能', '技術', '기술'), topic.society, 'N3'),
  vocab('kanri', '管理', 'かんり', 'kanri', text('Management', '管理', '管理', '관리'), topic.society, 'N3'),
  vocab('shutoku', '取得', 'しゅとく', 'shutoku', text('Acquisition', '取得', '取得', '취득'), topic.growth, 'N3'),
  vocab('kakudai', '拡大', 'かくだい', 'kakudai', text('Expansion', '扩大', '拡大', '확대'), topic.growth, 'N3'),
  vocab('shukushou', '縮小', 'しゅくしょう', 'shukushou', text('Reduction', '缩小', '縮小', '축소'), topic.growth, 'N3'),
  vocab('katsudou', '活動', 'かつどう', 'katsudou', text('Activity', '活动', '活動', '활동'), topic.society, 'N3'),
  vocab('houhou', '方法', 'ほうほう', 'houhou', text('Method', '方法', '方法', '방법'), topic.plans, 'N3'),
  vocab('tsuujiru', '通じる', 'つうじる', 'tsuujiru', text('Be understood', '能被理解/相通', '通じる', '통하다'), topic.verb, 'N3'),
  vocab('mitsukaru', '見つかる', 'みつかる', 'mitsukaru', text('Be found', '被找到', '見つかる', '발견되다'), topic.verb, 'N3'),
  vocab('uketoru', '受け取る', 'うけとる', 'uketoru', text('Receive', '接收/领取', '受け取る', '받다'), topic.verb, 'N3'),
  vocab('kaifuku', '回復', 'かいふく', 'kaifuku', text('Recovery', '恢复', '回復', '회복'), topic.growth, 'N3'),
  vocab('shuyou', '主要', 'しゅよう', 'shuyou', text('Main / major', '主要', '主要', '주요'), topic.abstract, 'N3'),
  vocab('sonzai', '存在', 'そんざい', 'sonzai', text('Existence', '存在', '存在', '존재'), topic.abstract, 'N3'),
  vocab('jishin', '自信', 'じしん', 'jishin', text('Confidence', '自信', '自信', '자신감'), topic.growth, 'N3'),
  vocab('seishin', '精神', 'せいしん', 'seishin', text('Mind / spirit', '精神', '精神', '정신'), topic.abstract, 'N3'),
  vocab('kansei', '完成', 'かんせい', 'kansei', text('Completion', '完成', '完成', '완성'), topic.growth, 'N3'),
  vocab('shuuchuu', '集中', 'しゅうちゅう', 'shuuchuu', text('Concentration', '集中', '集中', '집중'), topic.growth, 'N3'),
  vocab('kettei', '決定', 'けってい', 'kettei', text('Decision', '决定', '決定', '결정'), topic.plans, 'N3'),
  vocab('koukan', '交換', 'こうかん', 'koukan', text('Exchange', '交换', '交換', '교환'), topic.society, 'N3'),
  vocab('souzou-imagination', '想像', 'そうぞう', 'souzou', text('Imagination', '想象', '想像', '상상'), topic.abstract, 'N3'),
  vocab('kanjou', '感情', 'かんじょう', 'kanjou', text('Emotion', '感情', '感情', '감정'), topic.feeling, 'N3'),
  vocab('rikai', '理解', 'りかい', 'rikai', text('Understanding', '理解', '理解', '이해'), topic.abstract, 'N3'),
  vocab('setsuyaku', '節約', 'せつやく', 'setsuyaku', text('Saving / economizing', '节约', '節約', '절약'), topic.daily, 'N3'),
  vocab('chousen', '挑戦', 'ちょうせん', 'chousen', text('Challenge', '挑战', '挑戦', '도전'), topic.courage, 'N3'),
  vocab('kanousei', '可能性', 'かのうせい', 'kanousei', text('Possibility', '可能性', '可能性', '가능성'), topic.abstract, 'N3'),
  vocab('jissai', '実際', 'じっさい', 'jissai', text('Actually / reality', '实际/现实', '実際', '실제'), topic.abstract, 'N3'),
  vocab('taido', '態度', 'たいど', 'taido', text('Attitude', '态度', '態度', '태도'), topic.people, 'N3'),
  vocab('chishiki', '知識', 'ちしき', 'chishiki', text('Knowledge', '知识', '知識', '지식'), topic.school, 'N3'),
  vocab('hannou', '反応', 'はんのう', 'hannou', text('Reaction / response', '反应', '反応', '반응'), topic.society, 'N3'),
  vocab('kansatsu', '観察', 'かんさつ', 'kansatsu', text('Observation', '观察', '観察', '관찰'), topic.mystery, 'N3'),
  vocab('seiri', '整理', 'せいり', 'seiri', text('Organization / sorting', '整理', '整理', '정리'), topic.daily, 'N3'),
  vocab('kiroku', '記録', 'きろく', 'kiroku', text('Record / documentation', '记录', '記録', '기록'), topic.school, 'N3'),
  vocab('kyouryoku', '協力', 'きょうりょく', 'kyouryoku', text('Cooperation', '合作/协力', '協力', '협력'), topic.friendship, 'N3'),
  vocab('eikyou', '影響', 'えいきょう', 'eikyou', text('Influence', '影响', '影響', '영향'), topic.society, 'N2'),
  vocab('handan', '判断', 'はんだん', 'handan', text('Judgment', '判断', '判断', '판단'), topic.abstract, 'N2'),
  vocab('sekinin', '責任', 'せきにん', 'sekinin', text('Responsibility', '责任', '責任', '책임'), topic.society, 'N2'),
  vocab('joukyou', '状況', 'じょうきょう', 'joukyou', text('Situation', '状况', '状況', '상황'), topic.society, 'N2'),
  vocab('taishou', '対象', 'たいしょう', 'taishou', text('Target / subject', '对象/主题', '対象', '대상'), topic.abstract, 'N2'),
  vocab('kachi', '価値', 'かち', 'kachi', text('Value', '价值', '価値', '가치'), topic.abstract, 'N2'),
  vocab('kaizen', '改善', 'かいぜん', 'kaizen', text('Improvement', '改善', '改善', '개선'), topic.growth, 'N2'),
  vocab('bunseki', '分析', 'ぶんせき', 'bunseki', text('Analysis', '分析', '分析', '분석'), topic.abstract, 'N2'),
  vocab('genjitsu', '現実', 'げんじつ', 'genjitsu', text('Reality', '现实', '現実', '현실'), topic.abstract, 'N2'),
  vocab('henka', '変化', 'へんか', 'henka', text('Change / variation', '变化', '変化', '변화'), topic.growth, 'N2'),
  vocab('sentaku', '選択', 'せんたく', 'sentaku', text('Choice', '选择', '選択', '선택'), topic.plans, 'N2'),
  vocab('kadai', '課題', 'かだい', 'kadai', text('Task / issue', '课题/问题', '課題', '과제/문제'), topic.school, 'N2'),
  vocab('mitomeru', '認める', 'みとめる', 'mitomeru', text('Recognize / admit', '承认/认可', '認める', '인정하다'), topic.verb, 'N2'),
  vocab('sasaeru', '支える', 'ささえる', 'sasaeru', text('Support', '支撑/支持', '支える', '지탱하다/지원하다'), topic.verb, 'N2'),
  vocab('kotowaru', '断る', 'ことわる', 'kotowaru', text('Refuse', '拒绝', '断る', '거절하다'), topic.verb, 'N2'),
  vocab('norikoeru', '乗り越える', 'のりこえる', 'norikoeru', text('Overcome', '克服', '乗り越える', '극복하다'), topic.verb, 'N2'),
  vocab('seido', '制度', 'せいど', 'seido', text('System / institution', '制度', '制度', '제도'), topic.society, 'N2'),
  vocab('shudan', '手段', 'しゅだん', 'shudan', text('Means / method', '手段/方法', '手段', '수단'), topic.plans, 'N2'),
  vocab('yakuwari', '役割', 'やくわり', 'yakuwari', text('Role', '角色/职责', '役割', '역할'), topic.society, 'N2'),
  vocab('hihan', '批判', 'ひはん', 'hihan', text('Criticism', '批判', '批判', '비판'), topic.society, 'N2'),
  vocab('tenkai', '展開', 'てんかい', 'tenkai', text('Development / unfolding', '展开/发展', '展開', '전개'), topic.growth, 'N2'),
  vocab('ishiki', '意識', 'いしき', 'ishiki', text('Awareness / consciousness', '意识', '意識', '의식'), topic.abstract, 'N2'),
  vocab('chousa', '調査', 'ちょうさ', 'chousa', text('Investigation / survey', '调查', '調査', '조사'), topic.society, 'N2'),
  vocab('shoumei', '証明', 'しょうめい', 'shoumei', text('Proof', '证明', '証明', '증명'), topic.abstract, 'N2'),
  vocab('kouka', '効果', 'こうか', 'kouka', text('Effect', '效果', '効果', '효과'), topic.abstract, 'N2'),
  vocab('seisaku', '政策', 'せいさく', 'seisaku', text('Policy', '政策', '政策', '정책'), topic.society, 'N2'),
  vocab('keikou', '傾向', 'けいこう', 'keikou', text('Tendency', '倾向', '傾向', '경향'), topic.abstract, 'N2'),
  vocab('kijun', '基準', 'きじゅん', 'kijun', text('Standard / criterion', '标准/基准', '基準', '기준'), topic.abstract, 'N2'),
  vocab('youso', '要素', 'ようそ', 'youso', text('Element', '要素', '要素', '요소'), topic.abstract, 'N2'),
  vocab('kanten', '観点', 'かんてん', 'kanten', text('Viewpoint', '观点', '観点', '관점'), topic.abstract, 'N2'),
  vocab('katei', '過程', 'かてい', 'katei', text('Process', '过程', '過程', '과정'), topic.growth, 'N2'),
  vocab('jiritsu', '自立', 'じりつ', 'jiritsu', text('Independence', '自立', '自立', '자립'), topic.growth, 'N2'),
  vocab('sougo', '相互', 'そうご', 'sougo', text('Mutual', '相互', '相互', '상호'), topic.society, 'N2'),
  vocab('ijou', '異常', 'いじょう', 'ijou', text('Abnormality', '异常', '異常', '이상'), topic.nuance, 'N2'),
  vocab('izon', '依存', 'いぞん', 'izon', text('Dependence', '依赖', '依存', '의존'), topic.society, 'N2'),
  vocab('kijutsu', '記述', 'きじゅつ', 'kijutsu', text('Description / account', '记述/描述', '記述', '기술/서술'), topic.abstract, 'N2'),
  vocab('shori', '処理', 'しょり', 'shori', text('Processing', '处理', '処理', '처리'), topic.society, 'N2'),
  vocab('hatten', '発展', 'はってん', 'hatten', text('Development', '发展', '発展', '발전'), topic.growth, 'N2'),
  vocab('fukumeru', '含める', 'ふくめる', 'fukumeru', text('Include', '包括/包含', '含める', '포함하다'), topic.verb, 'N2'),
  vocab('michibiku', '導く', 'みちびく', 'michibiku', text('Guide / lead', '引导/带领', '導く', '이끌다'), topic.verb, 'N2'),
  vocab('shisou', '思想', 'しそう', 'shisou', text('Thought / ideology', '思想', '思想', '사상'), topic.abstract, 'N2'),
  vocab('ishi', '意思', 'いし', 'ishi', text('Intention / will', '意志/意向', '意思', '의사/뜻'), topic.abstract, 'N2'),
  vocab('taiou', '対応', 'たいおう', 'taiou', text('Response / handling', '应对/处理', '対応', '대응'), topic.society, 'N2'),
  vocab('kouzou', '構造', 'こうぞう', 'kouzou', text('Structure', '结构', '構造', '구조'), topic.abstract, 'N2'),
  vocab('bunya', '分野', 'ぶんや', 'bunya', text('Field / domain', '领域', '分野', '분야'), topic.society, 'N2'),
  vocab('shigen', '資源', 'しげん', 'shigen', text('Resources', '资源', '資源', '자원'), topic.society, 'N2'),
  vocab('jittai', '実態', 'じったい', 'jittai', text('Actual state', '实际状态', '実態', '실태'), topic.society, 'N2'),
  vocab('youkyuu', '要求', 'ようきゅう', 'youkyuu', text('Demand / request', '要求/请求', '要求', '요구'), topic.society, 'N2'),
  vocab('chousei', '調整', 'ちょうせい', 'chousei', text('Adjustment', '调整', '調整', '조정'), topic.plans, 'N2'),
  vocab('kouho', '候補', 'こうほ', 'kouho', text('Candidate', '候选/候补', '候補', '후보'), topic.people, 'N2'),
  vocab('kaitou', '回答', 'かいとう', 'kaitou', text('Answer / reply', '回答', '回答', '회답'), topic.question, 'N2'),
  vocab('shuchou', '主張', 'しゅちょう', 'shuchou', text('Claim / assertion', '主张', '主張', '주장'), topic.abstract, 'N2'),
  vocab('kousatsu', '考察', 'こうさつ', 'kousatsu', text('Consideration / analysis', '考察/分析', '考察', '고찰'), topic.abstract, 'N2'),
  vocab('sonchou', '尊重', 'そんちょう', 'sonchou', text('Respect', '尊重', '尊重', '존중'), topic.society, 'N2'),
  vocab('iji', '維持', 'いじ', 'iji', text('Maintenance', '维持', '維持', '유지'), topic.growth, 'N2'),
  vocab('suishin', '推進', 'すいしん', 'suishin', text('Promotion / advancement', '推进/促进', '推進', '추진'), topic.growth, 'N2'),
  vocab('hitei', '否定', 'ひてい', 'hitei', text('Negation / denial', '否定', '否定', '부정'), topic.abstract, 'N2'),
  vocab('kouken', '貢献', 'こうけん', 'kouken', text('Contribution', '贡献', '貢献', '공헌'), topic.society, 'N2'),
  vocab('sokushin', '促進', 'そくしん', 'sokushin', text('Acceleration / promotion', '促进/加速', '促進', '촉진'), topic.growth, 'N2'),
  vocab('youyaku', '要約', 'ようやく', 'youyaku', text('Summary', '摘要/概括', '要約', '요약'), topic.school, 'N2'),
  vocab('mujun', '矛盾', 'むじゅん', 'mujun', text('Contradiction', '矛盾', '矛盾', '모순'), topic.abstract, 'N1'),
  vocab('gainen', '概念', 'がいねん', 'gainen', text('Concept', '概念', '概念', '개념'), topic.abstract, 'N1'),
  vocab('honshitsu', '本質', 'ほんしつ', 'honshitsu', text('Essence', '本质', '本質', '본질'), topic.abstract, 'N1'),
  vocab('yoin', '余韻', 'よいん', 'yoin', text('Lingering impression', '余韵', '余韻', '여운'), topic.nuance, 'N1'),
  vocab('kattou', '葛藤', 'かっとう', 'kattou', text('Inner conflict', '内心冲突', '葛藤', '갈등'), topic.nuance, 'N1'),
  vocab('chimitsu', '緻密', 'ちみつ', 'chimitsu', text('Precise / meticulous', '缜密/精细', '緻密', '치밀함'), topic.nuance, 'N1'),
  vocab('hakanai', '儚い', 'はかない', 'hakanai', text('Fleeting', '短暂虚幻', '儚い', '덧없다'), topic.nuance, 'N1'),
  vocab('bakuzen', '漠然', 'ばくぜん', 'bakuzen', text('Vague', '模糊不清', '漠然', '막연함'), topic.nuance, 'N1'),
  vocab('dousatsu', '洞察', 'どうさつ', 'dousatsu', text('Insight', '洞察', '洞察', '통찰'), topic.abstract, 'N1'),
  vocab('rinkaku', '輪郭', 'りんかく', 'rinkaku', text('Outline / contour', '轮廓', '輪郭', '윤곽'), topic.nuance, 'N1'),
  vocab('kakugo', '覚悟', 'かくご', 'kakugo', text('Resolve', '觉悟', '覚悟', '각오'), topic.courage, 'N1'),
  vocab('kaishaku', '解釈', 'かいしゃく', 'kaishaku', text('Interpretation', '解释/解读', '解釈', '해석'), topic.abstract, 'N1'),
  vocab('tsuranuku', '貫く', 'つらぬく', 'tsuranuku', text('Carry through', '贯彻到底', '貫く', '관철하다'), topic.verb, 'N1'),
  vocab('kutsugaesu', '覆す', 'くつがえす', 'kutsugaesu', text('Overturn', '推翻', '覆す', '뒤집다'), topic.verb, 'N1'),
  vocab('mikiwameru', '見極める', 'みきわめる', 'mikiwameru', text('Discern', '看清/辨别', '見極める', '분별하다'), topic.verb, 'N1'),
  vocab('uketsugu', '受け継ぐ', 'うけつぐ', 'uketsugu', text('Inherit', '继承', '受け継ぐ', '이어받다'), topic.verb, 'N1'),
  vocab('rinen', '理念', 'りねん', 'rinen', text('Ideal / principle', '理念/原则', '理念', '이념'), topic.abstract, 'N1'),
  vocab('shoudou', '衝動', 'しょうどう', 'shoudou', text('Impulse', '冲动', '衝動', '충동'), topic.feeling, 'N1'),
  vocab('muishiki', '無意識', 'むいしき', 'muishiki', text('Unconsciousness', '无意识', '無意識', '무의식'), topic.abstract, 'N1'),
  vocab('kyouchou', '強調', 'きょうちょう', 'kyouchou', text('Emphasis', '强调', '強調', '강조'), topic.nuance, 'N1'),
  vocab('yuragu', '揺らぐ', 'ゆらぐ', 'yuragu', text('Waver / shake', '动摇/摇晃', '揺らぐ', '흔들리다'), topic.verb, 'N1'),
  vocab('sasayaku', '囁く', 'ささやく', 'sasayaku', text('Whisper', '低语', '囁く', '속삭이다'), topic.verb, 'N1'),
  vocab('tsukitomeru', '突き止める', 'つきとめる', 'tsukitomeru', text('Track down / determine', '查明/追究', '突き止める', '밝혀내다'), topic.verb, 'N1'),
  vocab('souzou', '創造', 'そうぞう', 'souzou', text('Creation', '创造', '創造', '창조'), topic.abstract, 'N1'),
  vocab('kyouchi', '境地', 'きょうち', 'kyouchi', text('State of mind', '境界/心境', '境地', '경지'), topic.nuance, 'N1'),
  vocab('yousha', '容赦', 'ようしゃ', 'yousha', text('Mercy', '宽恕/留情', '容赦', '용서/사정'), topic.nuance, 'N1'),
  vocab('shingi', '真偽', 'しんぎ', 'shingi', text('Truth or falsehood', '真假', '真偽', '진위'), topic.mystery, 'N1'),
  vocab('fukan', '俯瞰', 'ふかん', 'fukan', text("Bird's-eye view", '俯瞰', '俯瞰', '조망'), topic.abstract, 'N1'),
  vocab('henbou', '変貌', 'へんぼう', 'henbou', text('Transformation', '变貌/变化', '変貌', '변모'), topic.growth, 'N1'),
  vocab('kannen', '観念', 'かんねん', 'kannen', text('Idea / notion', '观念', '観念', '관념'), topic.abstract, 'N1'),
  vocab('chihei', '地平', 'ちへい', 'chihei', text('Horizon', '地平线', '地平', '지평'), topic.nature, 'N1'),
  vocab('suii', '推移', 'すいい', 'suii', text('Transition', '推移/变迁', '推移', '추이'), topic.abstract, 'N1'),
  vocab('sentan', '先端', 'せんたん', 'sentan', text('Frontier / tip', '前沿/尖端', '先端', '첨단/끝'), topic.society, 'N1'),
  vocab('taida', '怠惰', 'たいだ', 'taida', text('Laziness / apathy', '怠惰/懒散', '怠惰', '나태'), topic.feeling, 'N1'),
  vocab('honnou', '本能', 'ほんのう', 'honnou', text('Instinct', '本能', '本能', '본능'), topic.abstract, 'N1'),
  vocab('kyoumei', '共鳴', 'きょうめい', 'kyoumei', text('Resonance', '共鸣', '共鳴', '공명'), topic.nuance, 'N1'),
  vocab('shisaku', '思索', 'しさく', 'shisaku', text('Contemplation', '思索', '思索', '사색'), topic.abstract, 'N1'),
  vocab('bokyaku', '忘却', 'ぼうきゃく', 'bokyaku', text('Oblivion', '忘却', '忘却', '망각'), topic.nuance, 'N1'),
  vocab('kyozou', '虚像', 'きょぞう', 'kyozou', text('False image', '虚像', '虚像', '허상'), topic.mystery, 'N1'),
  vocab('kyoukai', '境界', 'きょうかい', 'kyoukai', text('Boundary', '边界', '境界', '경계'), topic.abstract, 'N1'),
  vocab('kiseki', '軌跡', 'きせき', 'kiseki', text('Trajectory / path', '轨迹', '軌跡', '궤적'), topic.nuance, 'N1'),
  vocab('houshin', '方針', 'ほうしん', 'houshin', text('Policy / direction', '方针/方向', '方針', '방침'), topic.plans, 'N1'),
  vocab('kikou', '機構', 'きこう', 'kikou', text('Mechanism / organization', '机制/机构', '機構', '기구/메커니즘'), topic.society, 'N1'),
  vocab('houkatsu', '包括', 'ほうかつ', 'houkatsu', text('Inclusion / comprehensiveness', '包括/总括', '包括', '포괄'), topic.abstract, 'N1'),
  vocab('tannou', '堪能', 'たんのう', 'tannou', text('Mastery / skillfulness', '精通/熟练', '堪能', '능숙함'), topic.growth, 'N1'),
  vocab('goui', '合意', 'ごうい', 'goui', text('Consensus / agreement', '共识/合意', '合意', '합의'), topic.society, 'N1'),
  vocab('sakugo', '錯誤', 'さくご', 'sakugo', text('Error / trial and error', '错误/试错', '錯誤', '착오'), topic.growth, 'N1'),
  vocab('kaimei', '解明', 'かいめい', 'kaimei', text('Clarification / elucidation', '阐明/解明', '解明', '해명/규명'), topic.mystery, 'N1'),
  vocab('jigo', '事後', 'じご', 'jigo', text('After the fact', '事后', '事後', '사후'), topic.time, 'N1'),
  vocab('anji', '暗示', 'あんじ', 'anji', text('Hint / suggestion', '暗示/提示', '暗示', '암시'), topic.mystery, 'N1'),
  vocab('keiki', '契機', 'けいき', 'keiki', text('Trigger / turning point', '契机/转折点', '契機', '계기'), topic.growth, 'N1'),
  vocab('issai', '一切', 'いっさい', 'issai', text('Everything / absolutely', '一切/完全', '一切', '일체'), topic.nuance, 'N1'),
  vocab('teigi', '定義', 'ていぎ', 'teigi', text('Definition', '定义', '定義', '정의'), topic.abstract, 'N1'),
  vocab('seiyaku', '制約', 'せいやく', 'seiyaku', text('Constraint / restriction', '制约/限制', '制約', '제약'), topic.abstract, 'N1'),
  vocab('taitou', '台頭', 'たいとう', 'taitou', text('Rise / emergence', '抬头/兴起', '台頭', '대두'), topic.society, 'N1'),
  vocab('teitai', '停滞', 'ていたい', 'teitai', text('Stagnation', '停滞', '停滞', '정체'), topic.growth, 'N1'),
  vocab('ichiren', '一連', 'いちれん', 'ichiren', text('Series / sequence', '一连串/系列', '一連', '일련'), topic.abstract, 'N1'),
  vocab('shihai', '支配', 'しはい', 'shihai', text('Control / domination', '支配/控制', '支配', '지배'), topic.society, 'N1'),
  vocab('saisei', '再生', 'さいせい', 'saisei', text('Regeneration / playback', '再生/重生', '再生', '재생'), topic.growth, 'N1'),
  vocab('hensan', '編纂', 'へんさん', 'hensan', text('Compilation / editing', '编纂/编辑', '編纂', '편찬'), topic.school, 'N1'),
  vocab('eiga', '映画', 'えいが', 'eiga', text('Movie', '电影', '映画', '영화'), topic.daily),
  vocab('ongaku', '音楽', 'おんがく', 'ongaku', text('Music', '音乐', '音楽', '음악'), topic.daily),
  vocab('shashin', '写真', 'しゃしん', 'shashin', text('Photo', '照片', '写真', '사진'), topic.object),
  vocab('heya', '部屋', 'へや', 'heya', text('Room', '房间', '部屋', '방'), topic.place),
  vocab('jikan', '時間', 'じかん', 'jikan', text('Time / hour', '时间/小时', '時間', '시간'), topic.time),
  vocab('kuruma', '車', 'くるま', 'kuruma', text('Car', '汽车', '車', '차'), topic.travel),
  vocab('jitensha', '自転車', 'じてんしゃ', 'jitensha', text('Bicycle', '自行车', '自転車', '자전거'), topic.travel),
  vocab('shiroi', '白い', 'しろい', 'shiroi', text('White', '白色的', '白い', '하얗다'), topic.adjective),
  vocab('kuroi', '黒い', 'くろい', 'kuroi', text('Black', '黑色的', '黒い', '검다'), topic.adjective),
  vocab('atarashii', '新しい', 'あたらしい', 'atarashii', text('New', '新的', '新しい', '새롭다'), topic.adjective),
  vocab('baai', '場合', 'ばあい', 'baai', text('Case / occasion', '情况/场合', '場合', '경우'), topic.plans, 'N4'),
  vocab('tsureteiku', '連れて行く', 'つれていく', 'tsurete iku', text('Take someone along', '带某人去', '連れて行く', '데려가다'), topic.travel, 'N4'),
  vocab('norikaeru', '乗り換える', 'のりかえる', 'norikaeru', text('Transfer / change trains', '换乘', '乗り換える', '갈아타다'), topic.travel, 'N4'),
  vocab('uketsuke', '受付', 'うけつけ', 'uketsuke', text('Reception desk', '接待/前台', '受付', '접수'), topic.place, 'N4'),
  vocab('juusho', '住所', 'じゅうしょ', 'juusho', text('Address', '住址', '住所', '주소'), topic.place, 'N4'),
  vocab('shuumatsu', '週末', 'しゅうまつ', 'shuumatsu', text('Weekend', '周末', '週末', '주말'), topic.time, 'N4'),
  vocab('isogu', '急ぐ', 'いそぐ', 'isogu', text('Hurry', '赶快/着急', '急ぐ', '서두르다'), topic.verb, 'N4'),
  vocab('tsugou', '都合', 'つごう', 'tsugou', text('Convenience / circumstances', '方便/情况', '都合', '사정/형편'), topic.plans, 'N4'),
  vocab('katazukeru', '片付ける', 'かたづける', 'katazukeru', text('Tidy up', '收拾/整理', '片付ける', '정리하다'), topic.verb, 'N4'),
  vocab('tashikameru', '確かめる', 'たしかめる', 'tashikameru', text('Check / confirm', '确认', '確かめる', '확인하다'), topic.verb, 'N4'),
  vocab('hataraki', '働き', 'はたらき', 'hataraki', text('Function / work', '作用/功能', '働き', '작용/기능'), topic.society, 'N3'),
  vocab('yakudatsu', '役立つ', 'やくだつ', 'yakudatsu', text('Be useful', '有用/起作用', '役立つ', '도움이 되다'), topic.verb, 'N3'),
  vocab('kyoutsuu', '共通', 'きょうつう', 'kyoutsuu', text('Common / shared', '共同/共通', '共通', '공통'), topic.abstract, 'N3'),
  vocab('renzoku', '連続', 'れんぞく', 'renzoku', text('Continuation / series', '连续', '連続', '연속'), topic.time, 'N3'),
  vocab('hikaku', '比較', 'ひかく', 'hikaku', text('Comparison', '比较', '比較', '비교'), topic.abstract, 'N3'),
  vocab('gutaiteki', '具体的', 'ぐたいてき', 'gutaiteki', text('Concrete / specific', '具体的', '具体的', '구체적'), topic.abstract, 'N3'),
  vocab('heikin', '平均', 'へいきん', 'heikin', text('Average', '平均', '平均', '평균'), topic.number, 'N3'),
  vocab('wariai', '割合', 'わりあい', 'wariai', text('Ratio / proportion', '比例/比率', '割合', '비율'), topic.number, 'N3'),
  vocab('kigen', '期限', 'きげん', 'kigen', text('Deadline / time limit', '期限', '期限', '기한'), topic.time, 'N3'),
  vocab('teian', '提案', 'ていあん', 'teian', text('Proposal', '提案', '提案', '제안'), topic.society, 'N3'),
  vocab('juyou', '需要', 'じゅよう', 'juyou', text('Demand / need', '需求', '需要', '수요'), topic.society, 'N2'),
  vocab('kyoukyuu', '供給', 'きょうきゅう', 'kyoukyuu', text('Supply', '供给', '供給', '공급'), topic.society, 'N2'),
  vocab('mujun-vocab', '矛盾', 'むじゅん', 'mujun', text('Contradiction', '矛盾', '矛盾', '모순'), topic.abstract, 'N2'),
  vocab('youin', '要因', 'よういん', 'youin', text('Factor / cause', '因素/要因', '要因', '요인'), topic.abstract, 'N2'),
  vocab('kenshou', '検証', 'けんしょう', 'kenshou', text('Verification', '验证/检验', '検証', '검증'), topic.mystery, 'N2'),
  vocab('sanshou', '参照', 'さんしょう', 'sanshou', text('Reference', '参照/参考', '参照', '참조'), topic.school, 'N2'),
  vocab('katei-hypothesis', '仮定', 'かてい', 'katei', text('Assumption / hypothesis', '假定/假设', '仮定', '가정'), topic.abstract, 'N2'),
  vocab('haikei', '背景', 'はいけい', 'haikei', text('Background / context', '背景/来龙去脉', '背景', '배경'), topic.abstract, 'N2'),
  vocab('tekiyou', '適用', 'てきよう', 'tekiyou', text('Application / apply', '适用/应用', '適用', '적용'), topic.society, 'N2'),
  vocab('kibo', '規模', 'きぼ', 'kibo', text('Scale / scope', '规模', '規模', '규모'), topic.society, 'N2'),
  vocab('sennyuukan', '先入観', 'せんにゅうかん', 'sennyuukan', text('Preconception', '成见/先入为主', '先入観', '선입견'), topic.nuance, 'N1'),
  vocab('chuushouteki', '抽象的', 'ちゅうしょうてき', 'chuushouteki', text('Abstract', '抽象的', '抽象的', '추상적'), topic.abstract, 'N1'),
  vocab('fukaketsu', '不可欠', 'ふかけつ', 'fukaketsu', text('Indispensable', '不可或缺', '不可欠', '불가결'), topic.nuance, 'N1'),
  vocab('bimyou', '微妙', 'びみょう', 'bimyou', text('Subtle / delicate', '微妙', '微妙', '미묘함'), topic.nuance, 'N1'),
  vocab('shinzui', '真髄', 'しんずい', 'shinzui', text('Essence / true spirit', '精髓', '真髄', '진수'), topic.abstract, 'N1'),
  vocab('kencho', '顕著', 'けんちょ', 'kencho', text('Remarkable / prominent', '显著', '顕著', '현저함'), topic.nuance, 'N1'),
  vocab('suikou', '遂行', 'すいこう', 'suikou', text('Execution / carrying out', '执行/完成', '遂行', '수행'), topic.growth, 'N1'),
  vocab('taikei', '体系', 'たいけい', 'taikei', text('System / framework', '体系/框架', '体系', '체계'), topic.abstract, 'N1'),
  vocab('choukou', '兆候', 'ちょうこう', 'choukou', text('Sign / omen', '征兆/迹象', '兆候', '징후'), topic.mystery, 'N1'),
  vocab('darenimo', '誰にも', 'だれにも', 'dare ni mo', text('To nobody / to anyone', '谁都/对谁也', '誰にも', '누구에게도'), topic.nuance, 'N1'),
  vocab('tegami', '手紙', 'てがみ', 'tegami', text('Letter / note', '信/便条', '手紙', '편지/쪽지'), topic.object),
  vocab('tokei', '時計', 'とけい', 'tokei', text('Clock / watch', '钟表/手表', '時計', '시계'), topic.object),
  vocab('neko', '猫', 'ねこ', 'neko', text('Cat', '猫', '猫', '고양이'), topic.people),
  vocab('inu', '犬', 'いぬ', 'inu', text('Dog', '狗', '犬', '개'), topic.people),
  vocab('akai', '赤い', 'あかい', 'akai', text('Red', '红色的', '赤い', '빨갛다'), topic.adjective),
  vocab('aoi', '青い', 'あおい', 'aoi', text('Blue', '蓝色的', '青い', '파랗다'), topic.adjective),
  vocab('yasui-price', '安い', 'やすい', 'yasui', text('Cheap', '便宜', '安い', '싸다'), topic.adjective),
  vocab('takai', '高い', 'たかい', 'takai', text('Expensive / tall', '贵/高', '高い', '비싸다/높다'), topic.adjective),
  vocab('mainichi', '毎日', 'まいにち', 'mainichi', text('Every day', '每天', '毎日', '매일'), topic.time),
  vocab('getsuyoubi', '月曜日', 'げつようび', 'getsuyoubi', text('Monday', '星期一', '月曜日', '월요일'), topic.time),
  vocab('kaisha', '会社', 'かいしゃ', 'kaisha', text('Company', '公司', '会社', '회사'), topic.society, 'N4'),
  vocab('tenki', '天気', 'てんき', 'tenki', text('Weather', '天气', '天気', '날씨'), topic.nature, 'N4'),
  vocab('undou', '運動', 'うんどう', 'undou', text('Exercise', '运动', '運動', '운동'), topic.daily, 'N4'),
  vocab('ryokou', '旅行', 'りょこう', 'ryokou', text('Travel / trip', '旅行', '旅行', '여행'), topic.travel, 'N4'),
  vocab('shachou', '社長', 'しゃちょう', 'shachou', text('President / company head', '社长/公司负责人', '社長', '사장'), topic.people, 'N4'),
  vocab('kanashii', '悲しい', 'かなしい', 'kanashii', text('Sad', '悲伤', '悲しい', '슬프다'), topic.feeling, 'N4'),
  vocab('ureshii', '嬉しい', 'うれしい', 'ureshii', text('Happy / glad', '高兴', '嬉しい', '기쁘다'), topic.feeling, 'N4'),
  vocab('nemui', '眠い', 'ねむい', 'nemui', text('Sleepy', '困倦', '眠い', '졸리다'), topic.feeling, 'N4'),
  vocab('kowai', '怖い', 'こわい', 'kowai', text('Scary', '可怕', '怖い', '무섭다'), topic.feeling, 'N4'),
  vocab('hikkosu', '引っ越す', 'ひっこす', 'hikkosu', text('Move house', '搬家', '引っ越す', '이사하다'), topic.verb, 'N4'),
  vocab('kouritsu', '効率', 'こうりつ', 'kouritsu', text('Efficiency', '效率', '効率', '효율'), topic.growth, 'N3'),
  vocab('kentou', '検討', 'けんとう', 'kentou', text('Consideration / review', '研究/讨论', '検討', '검토'), topic.abstract, 'N3'),
  vocab('keizoku', '継続', 'けいぞく', 'keizoku', text('Continuation', '继续/持续', '継続', '계속'), topic.growth, 'N3'),
  vocab('fuan', '不安', 'ふあん', 'fuan', text('Anxiety', '不安', '不安', '불안'), topic.feeling, 'N3'),
  vocab('shiji', '指示', 'しじ', 'shiji', text('Instruction / indication', '指示/指令', '指示', '지시'), topic.society, 'N3'),
  vocab('shorui', '書類', 'しょるい', 'shorui', text('Documents', '文件', '書類', '서류'), topic.school, 'N3'),
  vocab('chuumoku', '注目', 'ちゅうもく', 'chuumoku', text('Attention', '关注/注意', '注目', '주목'), topic.society, 'N3'),
  vocab('sousa', '操作', 'そうさ', 'sousa', text('Operation / handling', '操作/处理', '操作', '조작/운용'), topic.verb, 'N3'),
  vocab('housoku', '法則', 'ほうそく', 'housoku', text('Principle / law', '法则/规律', '法則', '법칙'), topic.abstract, 'N3'),
  vocab('gutairei', '具体例', 'ぐたいれい', 'gutairei', text('Concrete example', '具体例子', '具体例', '구체적인 예'), topic.school, 'N3'),
  vocab('sokutei', '測定', 'そくてい', 'sokutei', text('Measurement', '测定/测量', '測定', '측정'), topic.abstract, 'N2'),
  vocab('haichi', '配置', 'はいち', 'haichi', text('Placement / arrangement', '配置/安排', '配置', '배치'), topic.plans, 'N2'),
  vocab('kaishou', '解消', 'かいしょう', 'kaishou', text('Elimination / resolution', '消除/解决', '解消', '해소'), topic.growth, 'N2'),
  vocab('setsuritsu', '設立', 'せつりつ', 'setsuritsu', text('Establishment', '设立/成立', '設立', '설립'), topic.society, 'N2'),
  vocab('tenbou', '展望', 'てんぼう', 'tenbou', text('Outlook / prospect', '展望/前景', '展望', '전망'), topic.abstract, 'N2'),
  vocab('dantai', '団体', 'だんたい', 'dantai', text('Organization / group', '团体/组织', '団体', '단체'), topic.society, 'N2'),
  vocab('jizen', '事前', 'じぜん', 'jizen', text('In advance', '事先/提前', '事前', '사전'), topic.time, 'N2'),
  vocab('koushin', '更新', 'こうしん', 'koushin', text('Update / renewal', '更新', '更新', '갱신'), topic.growth, 'N2'),
  vocab('hogo', '保護', 'ほご', 'hogo', text('Protection', '保护', '保護', '보호'), topic.society, 'N2'),
  vocab('hakki', '発揮', 'はっき', 'hakki', text('Display / demonstration', '发挥/展示', '発揮', '발휘'), topic.growth, 'N2'),
  vocab('chouetsu', '超越', 'ちょうえつ', 'chouetsu', text('Transcendence', '超越', '超越', '초월'), topic.abstract, 'N1'),
  vocab('saikouchiku', '再構築', 'さいこうちく', 'saikouchiku', text('Reconstruction', '重构/再构筑', '再構築', '재구축'), topic.growth, 'N1'),
  vocab('yokusei', '抑制', 'よくせい', 'yokusei', text('Suppression', '抑制', '抑制', '억제'), topic.abstract, 'N1'),
  vocab('fuhen', '普遍', 'ふへん', 'fuhen', text('Universality', '普遍性', '普遍', '보편'), topic.abstract, 'N1'),
  vocab('katsubou', '渇望', 'かつぼう', 'katsubou', text('Longing', '渴望', '渇望', '갈망'), topic.feeling, 'N1'),
  vocab('gugen', '具現', 'ぐげん', 'gugen', text('Embodiment', '具现', '具現', '구현'), topic.abstract, 'N1'),
  vocab('senren', '洗練', 'せんれん', 'senren', text('Refinement', '洗练/精炼', '洗練', '세련'), topic.nuance, 'N1'),
  vocab('chokkan', '直感', 'ちょっかん', 'chokkan', text('Intuition', '直觉', '直感', '직감'), topic.nuance, 'N1'),
  vocab('attou', '圧倒', 'あっとう', 'attou', text('Overwhelming power', '压倒性力量', '圧倒', '압도'), topic.courage, 'N1'),
  vocab('dousatsuryoku', '洞察力', 'どうさつりょく', 'dousatsuryoku', text('Insightful judgment', '洞察力/判断力', '洞察力', '통찰력'), topic.abstract, 'N1'),
  vocab('ushiro', '後ろ', 'うしろ', 'ushiro', text('Behind', '后面', '後ろ', '뒤'), topic.place),
  vocab('mae', '前', 'まえ', 'mae', text('Front / before', '前面/之前', '前', '앞/이전'), topic.place),
  vocab('hidari', '左', 'ひだり', 'hidari', text('Left', '左边', '左', '왼쪽'), topic.place),
  vocab('migi', '右', 'みぎ', 'migi', text('Right', '右边', '右', '오른쪽'), topic.place),
  vocab('naka', '中', 'なか', 'naka', text('Inside', '里面', '中', '안'), topic.place),
  vocab('soto', '外', 'そと', 'soto', text('Outside', '外面', '外', '밖'), topic.place),
  vocab('takusan', 'たくさん', 'たくさん', 'takusan', text('A lot', '很多', 'たくさん', '많이'), topic.number),
  vocab('sukoshi', '少し', 'すこし', 'sukoshi', text('A little', '一点', '少し', '조금'), topic.number),
  vocab('mou', 'もう', 'もう', 'mou', text('Again / already', '再/已经', 'もう', '다시/벌써'), topic.time),
  vocab('issho', '一緒', 'いっしょ', 'issho', text('Together', '一起', '一緒', '함께'), topic.friendship),
  vocab('shurui', '種類', 'しゅるい', 'shurui', text('Type / kind', '种类', '種類', '종류'), topic.object, 'N4'),
  vocab('kaisuu', '回数', 'かいすう', 'kaisuu', text('Number of times', '次数', '回数', '횟수'), topic.number, 'N4'),
  vocab('seikatsu', '生活', 'せいかつ', 'seikatsu', text('Daily living', '生活', '生活', '생활'), topic.daily, 'N4'),
  vocab('tsukiau', '付き合う', 'つきあう', 'tsukiau', text('Associate with', '交往/相处', '付き合う', '사귀다/어울리다'), topic.people, 'N4'),
  vocab('shinjiru', '信じる', 'しんじる', 'shinjiru', text('Believe', '相信', '信じる', '믿다'), topic.verb, 'N4'),
  vocab('nageru', '投げる', 'なげる', 'nageru', text('Throw', '投/扔', '投げる', '던지다'), topic.verb, 'N4'),
  vocab('kowareru', '壊れる', 'こわれる', 'kowareru', text('Break', '坏掉', '壊れる', '고장나다'), topic.verb, 'N4'),
  vocab('chigau', '違う', 'ちがう', 'chigau', text('Differ', '不同/不一样', '違う', '다르다'), topic.verb, 'N4'),
  vocab('fukuzatsu', '複雑', 'ふくざつ', 'fukuzatsu', text('Complex', '复杂', '複雑', '복잡함'), topic.adjective, 'N4'),
  vocab('daiji', '大事', 'だいじ', 'daiji', text('Important thing', '重要的事', '大事', '중요한 것'), topic.feeling, 'N4'),
  vocab('shakaiteki', '社会的', 'しゃかいてき', 'shakaiteki', text('Social', '社会性的', '社会的', '사회적'), topic.society, 'N3'),
  vocab('nouryoku', '能力', 'のうりょく', 'nouryoku', text('Ability', '能力', '能力', '능력'), topic.growth, 'N3'),
  vocab('keikaku', '計画', 'けいかく', 'keikaku', text('Planning', '计划安排', '計画', '계획'), topic.plans, 'N3'),
  vocab('hyouka', '評価', 'ひょうか', 'hyouka', text('Evaluation', '评价', '評価', '평가'), topic.society, 'N3'),
  vocab('mondaiten', '問題点', 'もんだいてん', 'mondaiten', text('Problem point', '问题点', '問題点', '문제점'), topic.abstract, 'N3'),
  vocab('renkei', '連携', 'れんけい', 'renkei', text('Coordination', '协作/联动', '連携', '연계'), topic.friendship, 'N3'),
  vocab('jouhou', '情報', 'じょうほう', 'jouhou', text('Information', '信息', '情報', '정보'), topic.society, 'N3'),
  vocab('hatsugen', '発言', 'はつげん', 'hatsugen', text('Statement / remark', '发言/言论', '発言', '발언'), topic.society, 'N3'),
  vocab('setsumeikai', '説明会', 'せつめいかい', 'setsumeikai', text('Briefing session', '说明会', '説明会', '설명회'), topic.school, 'N3'),
  vocab('hanashiai', '話し合い', 'はなしあい', 'hanashiai', text('Discussion', '商量/讨论', '話し合い', '논의'), topic.society, 'N3'),
  vocab('senryaku', '戦略', 'せんりゃく', 'senryaku', text('Strategy', '战略/策略', '戦略', '전략'), topic.society, 'N2'),
  vocab('taisei', '体制', 'たいせい', 'taisei', text('Structure / regime', '体制/结构', '体制', '체제'), topic.society, 'N2'),
  vocab('shisaku-policy', '施策', 'しさく', 'shisaku', text('Policy measure', '政策措施', '施策', '시책'), topic.society, 'N2'),
  vocab('kousou', '構想', 'こうそう', 'kousou', text('Concept / plan', '构想/规划', '構想', '구상'), topic.abstract, 'N2'),
  vocab('riron', '理論', 'りろん', 'riron', text('Theory', '理论', '理論', '이론'), topic.abstract, 'N2'),
  vocab('jizokusei', '持続性', 'じぞくせい', 'jizokusei', text('Sustainability', '持续性', '持続性', '지속성'), topic.growth, 'N2'),
  vocab('sougouteki', '総合的', 'そうごうてき', 'sougouteki', text('Comprehensive', '综合性的', '総合的', '종합적'), topic.abstract, 'N2'),
  vocab('saikentou', '再検討', 'さいけんとう', 'saikentou', text('Reconsideration', '重新讨论/再研究', '再検討', '재검토'), topic.growth, 'N2'),
  vocab('jiritsusei', '自立性', 'じりつせい', 'jiritsusei', text('Autonomy', '自立性', '自立性', '자립성'), topic.growth, 'N2'),
  vocab('yuusensei', '優先性', 'ゆうせんせい', 'yuusensei', text('Priority', '优先性', '優先性', '우선성'), topic.plans, 'N2'),
  vocab('shouchou', '象徴', 'しょうちょう', 'shouchou', text('Symbol', '象征', '象徴', '상징'), topic.nuance, 'N1'),
  vocab('kikikanri', '危機管理', 'ききかんり', 'kiki kanri', text('Crisis management', '危机管理', '危機管理', '위기관리'), topic.society, 'N1'),
  vocab('shutaisei', '主体性', 'しゅたいせい', 'shutaisei', text('Initiative / agency', '主体性/主动性', '主体性', '주체성'), topic.abstract, 'N1'),
  vocab('chuukakugainen', '中核概念', 'ちゅうかくがいねん', 'chuukaku gainen', text('Core concept', '核心概念', '中核概念', '핵심 개념'), topic.abstract, 'N1'),
  vocab('sougouhandan', '総合判断', 'そうごうはんだん', 'sougou handan', text('Comprehensive judgment', '综合判断', '総合判断', '종합 판단'), topic.abstract, 'N1'),
  vocab('shikoukatei', '思考過程', 'しこうかてい', 'shikou katei', text('Thought process', '思考过程', '思考過程', '사고 과정'), topic.abstract, 'N1'),
  vocab('gengoka', '言語化', 'げんごか', 'gengoka', text('Verbalization', '语言化/表达成语言', '言語化', '언어화'), topic.nuance, 'N1'),
  vocab('saisentanka', '最先端化', 'さいせんたんか', 'saisentanka', text('Cutting-edge shift', '尖端化', '最先端化', '첨단화'), topic.society, 'N1'),
  vocab('ninshikisoui', '認識相違', 'にんしきそうい', 'ninshiki soui', text('Difference in perception', '认知差异', '認識相違', '인식 차이'), topic.abstract, 'N1'),
  vocab('yuugousei', '融合性', 'ゆうごうせい', 'yuugousei', text('Integrative quality', '融合性', '融合性', '융합성'), topic.nuance, 'N1'),
  vocab('shio', '塩', 'しお', 'shio', text('Salt', '盐', '塩', '소금'), topic.food),
  vocab('satou', '砂糖', 'さとう', 'satou', text('Sugar', '糖', '砂糖', '설탕'), topic.food),
  vocab('iriguchi', '入口', 'いりぐち', 'iriguchi', text('Entrance', '入口', '入口', '입구'), topic.place),
  vocab('deguchi', '出口', 'でぐち', 'deguchi', text('Exit', '出口', '出口', '출구'), topic.place),
  vocab('keshiki', '景色', 'けしき', 'keshiki', text('Scenery', '景色', '景色', '경치'), topic.nature, 'N4'),
  vocab('machigai', '間違い', 'まちがい', 'machigai', text('Mistake', '错误', '間違い', '실수'), topic.daily, 'N4'),
  vocab('oshirase', 'お知らせ', 'おしらせ', 'oshirase', text('Notice / announcement', '通知/公告', 'お知らせ', '알림/공지'), topic.society, 'N4'),
  vocab('shiai', '試合', 'しあい', 'shiai', text('Match / game', '比赛', '試合', '시합'), topic.daily, 'N4'),
  vocab('shouko', '証拠', 'しょうこ', 'shouko', text('Evidence / proof', '证据/证明', '証拠', '증거'), topic.mystery, 'N3'),
  vocab('hyougen', '表現', 'ひょうげん', 'hyougen', text('Expression', '表达/表现', '表現', '표현'), topic.nuance, 'N3'),
  vocab('shourai', '将来', 'しょうらい', 'shourai', text('Future / in the future', '将来/未来', '将来', '장래/미래'), topic.plans, 'N3'),
  vocab('bunrui', '分類', 'ぶんるい', 'bunrui', text('Classification', '分类', '分類', '분류'), topic.abstract, 'N3'),
  vocab('gimu', '義務', 'ぎむ', 'gimu', text('Obligation', '义务', '義務', '의무'), topic.society, 'N2'),
  vocab('kanren', '関連', 'かんれん', 'kanren', text('Relatedness', '关联/相关性', '関連', '관련성'), topic.abstract, 'N2'),
  vocab('suijun', '水準', 'すいじゅん', 'suijun', text('Level / standard', '水准/标准', '水準', '수준'), topic.abstract, 'N2'),
  vocab('haibun', '配分', 'はいぶん', 'haibun', text('Distribution / allocation', '分配/配置', '配分', '배분'), topic.plans, 'N2'),
  vocab('gyakusetsu', '逆説', 'ぎゃくせつ', 'gyakusetsu', text('Paradox', '悖论/反论', '逆説', '역설'), topic.abstract, 'N1'),
  vocab('chikuseki', '蓄積', 'ちくせき', 'chikuseki', text('Accumulation', '积累', '蓄積', '축적'), topic.growth, 'N1'),
  vocab('yojou', '余剰', 'よじょう', 'yojou', text('Surplus', '剩余/富余', '余剰', '잉여'), topic.abstract, 'N1'),
  vocab('taikeika', '体系化', 'たいけいか', 'taikeika', text('Systematization', '体系化', '体系化', '체계화'), topic.abstract, 'N1'),
];

export const LINE_ITEMS: StudyItem[] = [
  line('mada-owarenai', 'まだ終われない', 'まだおわれない', 'mada owarenai', text("This can't end yet", '还不能结束', 'まだここで終わらない', '아직 끝낼 수 없어'), topic.courage),
  line('kokoro-orenai', '心は折れない', 'こころはおれない', 'kokoro wa orenai', text("My heart won't break", '心不会折断', '心は折れない', '마음은 꺾이지 않아'), topic.courage),
  line('zenryoku-de-ikou', '全力で行こう', 'ぜんりょくでいこう', 'zenryoku de ikou', text("Let's go all out", '全力上吧', '全力で行こう', '전력으로 가자'), topic.courage),
  line('ima-koso-kawaru', '今こそ変わる', 'いまこそかわる', 'ima koso kawaru', text('Now is when I change', '现在正是改变的时候', '今こそ変わる時', '지금이야말로 변할 때'), topic.courage),
  line('yuuki-wa-koko', '勇気はここにある', 'ゆうきはここにある', 'yuuki wa koko ni aru', text('Courage is right here', '勇气就在这里', '勇気はここにある', '용기는 여기에 있어'), topic.courage),
  line('nakama-wo-shinjiru', '仲間を信じる', 'なかまをしんじる', 'nakama wo shinjiru', text('Trust your friends', '相信伙伴', '仲間を信じる', '동료를 믿어'), topic.friendship),
  line('yakusoku-wa-mamoru', '約束は守る', 'やくそくはまもる', 'yakusoku wa mamoru', text('I keep my promises', '约定一定会守护', '約束は守る', '약속은 지켜'), topic.friendship),
  line('kimi-nara-dekiru', '君ならできる', 'きみならできる', 'kimi nara dekiru', text('You can do it', '如果是你就能做到', '君ならできる', '너라면 할 수 있어'), topic.friendship),
  line('kono-te-wo-hanasanai', 'この手を離さない', 'このてをはなさない', 'kono te wo hanasanai', text("I won't let go of this hand", '我不会放开这只手', 'この手を離さない', '이 손을 놓지 않을 거야'), topic.friendship),
  line('egao-wo-wasurenai', '笑顔を忘れない', 'えがおをわすれない', 'egao wo wasurenai', text("Don't forget your smile", '不要忘记笑容', '笑顔を忘れない', '웃음을 잊지 마'), topic.friendship),
  line('kaze-ga-yondeiru', '風が呼んでいる', 'かぜがよんでいる', 'kaze ga yonde iru', text('The wind is calling', '风在呼唤', '風が呼んでいる', '바람이 부르고 있어'), topic.adventure),
  line('hikari-wo-sagasou', '光を探そう', 'ひかりをさがそう', 'hikari wo sagasou', text("Let's search for the light", '去寻找光吧', '光を探そう', '빛을 찾자'), topic.adventure),
  line('sora-made-todoke', '空まで届け', 'そらまでとどけ', 'sora made todoke', text('Reach the sky', '传达到天空吧', '空まで届け', '하늘까지 닿아라'), topic.adventure),
  line('mirai-wo-tsukame', '未来をつかめ', 'みらいをつかめ', 'mirai wo tsukame', text('Grab the future', '抓住未来', '未来をつかめ', '미래를 붙잡아'), topic.adventure),
  line('hoshi-ga-terasu', '星が道を照らす', 'ほしがみちをてらす', 'hoshi ga michi wo terasu', text('Stars light the path', '星星照亮道路', '星が道を照らす', '별이 길을 비춰'), topic.adventure),
  line('koko-kara-hajimaru', 'ここから始まる', 'ここからはじまる', 'koko kara hajimaru', text('It starts here', '从这里开始', 'ここから始まる', '여기서 시작돼'), topic.schoolLine),
  line('shizuka-na-houkago', '静かな放課後', 'しずかなほうかご', 'shizuka na houkago', text('A quiet after school', '安静的放学后', '静かな放課後', '조용한 방과 후'), topic.schoolLine),
  line('ashita-wo-erabu', '明日を選ぶ', 'あしたをえらぶ', 'ashita wo erabu', text('Choose tomorrow', '选择明天', '明日を選ぶ', '내일을 선택해'), topic.schoolLine),
  line('ippo-zutsu-tsuyoku', '一歩ずつ強くなる', 'いっぽずつつよくなる', 'ippo zutsu tsuyoku naru', text('Grow stronger step by step', '一步步变强', '一歩ずつ強くなる', '한 걸음씩 강해져'), topic.schoolLine),
  line('yume-made-hashire', '夢まで走れ', 'ゆめまではしれ', 'yume made hashire', text('Run toward your dream', '向梦想奔跑', '夢まで走れ', '꿈까지 달려'), topic.schoolLine),
  line('himitsu-wa-mune', '秘密は胸の中', 'ひみつはむねのなか', 'himitsu wa mune no naka', text('The secret stays in my heart', '秘密藏在心里', '秘密は胸の中', '비밀은 마음속에'), topic.mystery),
  line('nazo-ga-ugoku', '謎が動き出す', 'なぞがうごきだす', 'nazo ga ugokidasu', text('The mystery begins to move', '谜团开始动了', '謎が動き出す', '수수께끼가 움직이기 시작해'), topic.mystery),
  line('kage-wo-oikake', '影を追いかける', 'かげをおいかける', 'kage wo oikakeru', text('Chase the shadow', '追逐影子', '影を追いかける', '그림자를 쫓아'), topic.mystery),
  line('shinjitsu-wa-chikai', '真実は近い', 'しんじつはちかい', 'shinjitsu wa chikai', text('The truth is close', '真相就在附近', '真実は近い', '진실은 가까워'), topic.mystery),
  line('kane-ga-mata-naru', '鐘がまた鳴る', 'かねがまたなる', 'kane ga mata naru', text('The bell rings again', '钟声再次响起', '鐘がまた鳴る', '종이 다시 울려'), topic.schoolLine),
  line('mou-ippo-mae-e', 'もう一歩前へ', 'もういっぽまえへ', 'mou ippo mae e', text('One more step forward', '再向前一步', 'もう一歩前へ', '한 걸음 더 앞으로'), topic.courage),
  line('monogatari-ga-hajimaru', '物語が始まる', 'ものがたりがはじまる', 'monogatari ga hajimaru', text('Our story begins', '我们的故事开始了', '物語が始まる', '우리의 이야기가 시작돼'), topic.adventure),
  line('kibou-wo-hanasanai', '希望を手放さない', 'きぼうをてばなさない', 'kibou wo tebanasanai', text('Hold on to hope', '抓住希望', '希望を手放さない', '희망을 놓지 마'), topic.courage),
  line('chiisana-hikari-wa-boku-no-mono', '小さな光は僕のもの', 'ちいさなひかりはぼくのもの', 'chiisana hikari wa boku no mono', text('This small light is mine', '这束小小的光属于我', '小さな光は僕のもの', '이 작은 빛은 내 거야'), topic.adventure),
  line('tobira-wa-ima-hiraku', '扉は今開く', 'とびらはいまひらく', 'tobira wa ima hiraku', text('The door opens now', '门现在打开', '扉は今開く', '문이 지금 열려'), topic.adventure),
  line('kowakunai-kokoro', '恐れを知らない心', 'おそれをしらないこころ', 'osore wo shiranai kokoro', text('No fear in my heart', '心中没有恐惧', '恐れを知らない心', '두렵지 않은 마음'), topic.courage),
  line('kyou-wo-mamoru', '今日を守る', 'きょうをまもる', 'kyou wo mamoru', text('I will protect today', '我要守护今天', '今日を守る', '오늘을 지킬 거야'), topic.friendship),
  line('hoshi-no-shita-de-aou', '星の下で会おう', 'ほしのしたであおう', 'hoshi no shita de aou', text('Meet me under the stars', '在星空下见吧', '星の下で会おう', '별 아래에서 만나'), topic.friendship),
  line('kotae-wa-naka-ni-aru', '答えは心の中にある', 'こたえはこころのなかにある', 'kotae wa kokoro no naka ni aru', text('The answer is within', '答案就在心中', '答えは心の中にある', '답은 안에 있어'), topic.mystery),
  line('ashita-wa-kagayaku', '明日は輝く', 'あしたはかがやく', 'ashita wa kagayaku', text('Tomorrow will shine', '明天会闪耀', '明日は輝く', '내일은 빛날 거야'), topic.schoolLine),
  line('kimi-no-koe-ga-kikoeru', '君の声が聞こえる', 'きみのこえがきこえる', 'kimi no koe ga kikoeru', text('I hear your voice', '我听见你的声音', '君の声が聞こえる', '네 목소리가 들려'), topic.friendship),
  line('chizu-wa-te-no-naka', '地図は手の中', 'ちずはてのなか', 'chizu wa te no naka', text('The map is in my hand', '地图就在手中', '地図は手の中', '지도는 손안에 있어'), topic.adventure),
  line('ame-wa-yakusoku-wo-kakusu', '雨は約束を隠す', 'あめはやくそくをかくす', 'ame wa yakusoku wo kakusu', text('The rain hides a promise', '雨中藏着约定', '雨は約束を隠す', '비는 약속을 숨겨'), topic.mystery),
  line('taorete-mo-tachiagaru', '倒れても立ち上がる', 'たおれてもたちあがる', 'taorete mo tachiagaru', text('We rise after falling', '跌倒也会站起来', '倒れても立ち上がる', '넘어져도 일어나'), topic.courage),
  line('kono-michi-wa-bokura-no-mono', 'この道は僕らのもの', 'このみちはぼくらのもの', 'kono michi wa bokura no mono', text('This path is ours', '这条路属于我们', 'この道は僕らのもの', '이 길은 우리의 것'), topic.adventure),
  line('atarashii-peeji-ga-hiraku', '新しいページが開く', 'あたらしいぺーじがひらく', 'atarashii peeji ga hiraku', text('A new chapter opens', '新的篇章打开了', '新しいページが開く', '새로운 페이지가 열려'), topic.schoolLine),
  line('hashire-chiisana-kokoro', '走れ小さな心', 'はしれちいさなこころ', 'hashire chiisana kokoro', text('Keep running, little heart', '奔跑吧小小的心', '走れ小さな心', '달려라 작은 마음'), topic.courage),
  line('yotei-wa-kaerareru', '予定はまだ変えられる', 'よていはまだかえられる', 'yotei wa mada kaerareru', text('The plan can still change', '计划还可以改变', '予定はまだ変えられる', '계획은 아직 바꿀 수 있어'), topic.plans, 'N4'),
  line('shippai-shite-mo-daijoubu', '失敗しても大丈夫', 'しっぱいしてもだいじょうぶ', 'shippai shite mo daijoubu', text('It is okay to fail', '失败也没关系', '失敗しても大丈夫', '실패해도 괜찮아'), topic.growth, 'N4'),
  line('yakusoku-no-basho-de', '約束の場所で待っている', 'やくそくのばしょでまっている', 'yakusoku no basho de matte iru', text('I am waiting at the promised place', '我在约定的地方等你', '約束の場所で待っている', '약속한 장소에서 기다리고 있어'), topic.friendship, 'N4'),
  line('kimi-no-iken-wo-kikasete', '君の意見を聞かせて', 'きみのいけんをきかせて', 'kimi no iken wo kikasete', text('Let me hear your opinion', '让我听听你的意见', '君の意見を聞かせて', '네 의견을 들려줘'), topic.daily, 'N4'),
  line('junbi-ga-dekitara-hashirou', '準備ができたら走ろう', 'じゅんびができたらはしろう', 'junbi ga dekitara hashirou', text('When we are ready, let us run', '准备好了就奔跑吧', '準備ができたら走ろう', '준비되면 달리자'), topic.courage, 'N4'),
  line('atarashii-michi-wo-erabou', '新しい道を選ぼう', 'あたらしいみちをえらぼう', 'atarashii michi wo erabou', text('Let us choose a new path', '选择一条新的路吧', '新しい道を選ぼう', '새로운 길을 고르자'), topic.adventure, 'N4'),
  line('watashi-wo-shoukai-suru', '私を紹介してくれる？', 'わたしをしょうかいしてくれる', 'watashi wo shoukai shite kureru', text('Will you introduce me?', '可以介绍我吗？', '私を紹介してくれる？', '나를 소개해 줄래?'), topic.friendship, 'N4'),
  line('shoutai-wa-yuuki-no-hajimari', '招待は勇気の始まりだ', 'しょうたいはゆうきのはじまりだ', 'shoutai wa yuuki no hajimari da', text('An invitation is where courage begins', '邀请是勇气的开始', '招待は勇気の始まりだ', '초대는 용기의 시작이야'), topic.courage, 'N4'),
  line('kisoku-no-naka-de-hikaru', '規則の中でも光れる', 'きそくのなかでもひかれる', 'kisoku no naka demo hikareru', text('You can shine even inside the rules', '在规则之中也能发光', '規則の中でも光れる', '규칙 안에서도 빛날 수 있어'), topic.schoolLine, 'N4'),
  line('oboeta-namae-wa-chikara', '覚えた名前は力になる', 'おぼえたなまえはちからになる', 'oboeta namae wa chikara ni naru', text('A remembered name becomes strength', '记住的名字会变成力量', '覚えた名前は力になる', '기억한 이름은 힘이 돼'), topic.friendship, 'N4'),
  line('taisetsu-na-kimochi', '大切な気持ちは伝えよう', 'たいせつなきもちはつたえよう', 'taisetsu na kimochi wa tsutaeyou', text('Convey your important feelings', '把重要的心情传达出去', '大切な気持ちは伝えよう', '소중한 마음을 전하자'), topic.friendship, 'N4'),
  line('henji-wa-kaze-yori-hayaku', '返事は風より早く', 'へんじはかぜよりはやく', 'henji wa kaze yori hayaku', text('Reply faster than the wind', '回复比风更快', '返事は風より早く', '바람보다 빠르게 답장해'), topic.adventure, 'N4'),
  line('okurete-mo-akiramenai', '遅れても諦めない', 'おくれてもあきらめない', 'okurete mo akiramenai', text('Even if I am late, I will not give up', '就算迟到也不放弃', '遅れても諦めない', '늦어도 포기하지 않아'), topic.courage, 'N4'),
  line('jugyou-no-ato-de-aou', '授業の後で会おう', 'じゅぎょうのあとであおう', 'jugyou no ato de aou', text('Let us meet after class', '下课后见吧', '授業の後で会おう', '수업 후에 만나자'), topic.schoolLine, 'N4'),
  line('kankou-no-asa-ga-hajimaru', '観光の朝が始まる', 'かんこうのあさがはじまる', 'kankou no asa ga hajimaru', text('The sightseeing morning begins', '观光的早晨开始了', '観光の朝が始まる', '관광의 아침이 시작돼'), topic.travel, 'N4'),
  line('shitsumon-sureba-michi-wa-hiraku', '質問すれば道は開く', 'しつもんすればみちはひらく', 'shitsumon sureba michi wa hiraku', text('Ask a question and the path opens', '只要提问道路就会打开', '質問すれば道は開く', '질문하면 길이 열린다'), topic.schoolLine, 'N4'),
  line('ryouri-no-nioi-de-kaerou', '料理の匂いが僕らを家へ呼ぶ', 'りょうりのにおいがぼくらをいえへよぶ', 'ryouri no nioi ga bokura wo ie e yobu', text('The smell of cooking calls us home', '料理的香气叫我们回家', '料理の匂いが僕らを家へ呼ぶ', '요리 냄새를 따라 집으로 가자'), topic.food, 'N4'),
  line('shumi-ga-ashita-wo-akaruku', '趣味が明日を明るくする', 'しゅみがあしたをあかるくする', 'shumi ga ashita wo akaruku suru', text('A hobby makes tomorrow brighter', '兴趣让明天更明亮', '趣味が明日を明るくする', '취미가 내일을 밝게 해'), topic.daily, 'N4'),
  line('shiken-no-mae-demo-waraeru', '試験の前でも笑える', 'しけんのまえでもわらえる', 'shiken no mae demo waraeru', text('I can smile even before the exam', '考试前也能笑出来', '試験の前でも笑える', '시험 전에도 웃을 수 있어'), topic.schoolLine, 'N4'),
  line('futsuu-no-hi-koso-takaramono', '普通の日こそ宝物だ', 'ふつうのひこそたからものだ', 'futsuu no hi koso takaramono da', text('An ordinary day is the real treasure', '平凡的一天才是真正的宝物', '普通の日こそ宝物だ', '평범한 날이야말로 보물이야'), topic.feeling, 'N4'),
  line('kiken-nara-te-wo-nobashite', '危険なら手を伸ばして', 'きけんならてをのばして', 'kiken nara te wo nobashite', text('If it is dangerous, reach for my hand', '如果有危险就伸出手', '危険なら手を伸ばして', '위험하면 손을 뻗어'), topic.friendship, 'N4'),
  line('kantan-ja-nakute-mo-susumou', '簡単じゃなくても進もう', 'かんたんじゃなくてもすすもう', 'kantan ja nakute mo susumou', text('Even if it is not simple, keep going', '就算不简单也继续前进', '簡単じゃなくても進もう', '간단하지 않아도 나아가자'), topic.courage, 'N4'),
  line('kimi-ga-naku-nara-tonari-ni-iru', '君が泣くなら隣にいる', 'きみがなくならとなりにいる', 'kimi ga naku nara tonari ni iru', text('If you cry, I will stay beside you', '如果你哭了我会待在你身边', '君が泣くなら隣にいる', '네가 울면 곁에 있을게'), topic.friendship, 'N4'),
  line('okutta-kotoba-ga-todoku-made', '送った言葉が届くまで', 'おくったことばがとどくまで', 'okutta kotoba ga todoku made', text('Until the words I sent reach you', '直到送出的心意传达到你那里', '送った言葉が届くまで', '보낸 말이 닿을 때까지'), topic.friendship, 'N4'),
  line('kotae-wa-hitotsu-ja-nai', '答えは一つじゃない', 'こたえはひとつじゃない', 'kotae wa hitotsu ja nai', text('There is not only one answer', '答案不只有一个', '答えは一つじゃない', '답은 하나뿐이 아니야'), topic.abstract, 'N3'),
  line('doryoku-wa-shizuka-ni-hikaru', '努力は静かに光る', 'どりょくはしずかにひかる', 'doryoku wa shizuka ni hikaru', text('Effort shines quietly', '努力会安静地发光', '努力は静かに光る', '노력은 조용히 빛나'), topic.growth, 'N3'),
  line('mokuteki-wo-wasurenai', '目的を忘れなければ迷わない', 'もくてきをわすれなければまよわない', 'mokuteki wo wasurenakereba mayowanai', text('If you remember the purpose, you will not get lost', '不忘记目的就不会迷路', '目的を忘れなければ迷わない', '목적을 잊지 않으면 헤매지 않아'), topic.abstract, 'N3'),
  line('kitai-ga-senaka-wo-osu', '期待が背中を押す', 'きたいがせなかをおす', 'kitai ga senaka wo osu', text('Expectation pushes me forward', '期待推着我前进', '期待が背中を押す', '기대가 등을 밀어줘'), topic.feeling, 'N3'),
  line('bunka-wo-koete-waraou', '文化の違いを越えて笑おう', 'ぶんかのちがいをこえてわらおう', 'bunka no chigai wo koete waraou', text('Let us smile beyond cultural differences', '越过文化差异一起笑吧', '文化の違いを越えて笑おう', '문화의 차이를 넘어 웃자'), topic.society, 'N3'),
  line('shippai-no-riyuu-wo-ashita-e', '失敗の理由を明日の力に変える', 'しっぱいのりゆうをあしたのちからにかえる', 'shippai no riyuu wo ashita no chikara ni kaeru', text('Turn the reason for failure into strength for tomorrow', '把失败的理由化为明天的力量', '失敗の理由を明日の力に変える', '실패의 이유를 내일의 힘으로 바꿔'), topic.growth, 'N3'),
  line('kekka-yori-koudou-da', '結果より行動を信じる', 'けっかよりこうどうをしんじる', 'kekka yori koudou wo shinjiru', text('I trust action more than results', '比起结果我更相信行动', '結果より行動を信じる', '결과보다 행동을 믿어'), topic.growth, 'N3'),
  line('genin-wo-mitsukereba-kaerareru', '原因を見つければ変えられる', 'げんいんをみつければかえられる', 'genin wo mitsukereba kaerareru', text('If we find the cause, we can change it', '找到原因就能改变', '原因を見つければ変えられる', '원인을 찾으면 바꿀 수 있어'), topic.abstract, 'N3'),
  line('kankyou-ga-bokura-wo-sodateru', '環境が僕らを育てる', 'かんきょうがぼくらをそだてる', 'kankyou ga bokura wo sodateru', text('The environment helps us grow', '环境让我们成长', '環境が僕らを育てる', '환경이 우리를 키워 줘'), topic.society, 'N3'),
  line('kaiketsu-no-kagi-wa-koko', '解決の鍵はここにある', 'かいけつのかぎはここにある', 'kaiketsu no kagi wa koko ni aru', text('The key to the solution is here', '解决的钥匙就在这里', '解決の鍵はここにある', '해결의 열쇠는 여기에 있어'), topic.mystery, 'N3'),
  line('kibou-wa-riyuu-wo-koeru', '希望は理由を越える', 'きぼうはりゆうをこえる', 'kibou wa riyuu wo koeru', text('Hope goes beyond reason', '希望会越过理由', '希望は理由を越える', '희망은 이유를 넘어선다'), topic.courage, 'N3'),
  line('bunka-ga-kokoro-wo-tsunagu', '文化が心をつなぐ', 'ぶんかがこころをつなぐ', 'bunka ga kokoro wo tsunagu', text('Culture connects hearts', '文化连接心灵', '文化が心をつなぐ', '문화가 마음을 잇는다'), topic.society, 'N3'),
  line('katsudou-no-naka-de-mitsukaru', '答えは行動の中で見つかる', 'こたえはこうどうのなかでみつかる', 'kotae wa koudou no naka de mitsukaru', text('The answer is found through action', '答案会在行动中找到', '答えは行動の中で見つかる', '답은 행동 속에서 찾을 수 있어'), topic.growth, 'N3'),
  line('houhou-wa-hitotsu-ja-nai', '方法は一つじゃない', 'ほうほうはひとつじゃない', 'houhou wa hitotsu ja nai', text('There is more than one method', '方法不只有一个', '方法は一つじゃない', '방법은 하나뿐이 아니다'), topic.abstract, 'N3'),
  line('kaifuku-shita-kokoro-de-hashiru', '立ち直った心でもう一度走る', 'たちなおったこころでもういちどはしる', 'tachinaotta kokoro de mou ichido hashiru', text('I run once more with a healed heart', '带着重新振作的心再次奔跑', '立ち直った心でもう一度走る', '다시 일어선 마음으로 한 번 더 달려'), topic.growth, 'N3'),
  line('shuyou-na-michi-wo-erabu', '自分が信じる道を選ぶ', 'じぶんがしんじるみちをえらぶ', 'jibun ga shinjiru michi wo erabu', text('Choose the path you believe in', '选择自己相信的道路', '自分が信じる道を選ぶ', '자신이 믿는 길을 선택해'), topic.adventure, 'N3'),
  line('jishin-wa-shizuka-ni-sodatsu', '自信は静かに育つ', 'じしんはしずかにそだつ', 'jishin wa shizuka ni sodatsu', text('Confidence grows quietly', '自信会安静地成长', '自信は静かに育つ', '자신감은 조용히 자란다'), topic.growth, 'N3'),
  line('shuuchuu-sureba-kabe-wa-hikuku', '集中すれば壁は低くなる', 'しゅうちゅうすればかべはひくくなる', 'shuuchuu sureba kabe wa hikuku naru', text('Focus, and the wall becomes lower', '只要集中墙就会变低', '集中すれば壁は低くなる', '집중하면 벽은 낮아져'), topic.courage, 'N3'),
  line('kettei-no-shunkan-ni-kaze-ga-kawaru', '決定の瞬間に風が変わる', 'けっていのしゅんかんにかぜがかわる', 'kettei no shunkan ni kaze ga kawaru', text('The wind changes at the moment of decision', '决定的瞬间风向会改变', '決定の瞬間に風が変わる', '결정의 순간에 바람이 바뀐다'), topic.adventure, 'N3'),
  line('souzou-ga-tobira-wo-hiraku', '想像が扉を開く', 'そうぞうがとびらをひらく', 'souzou ga tobira wo hiraku', text('Imagination opens the door', '想象会打开门', '想像が扉を開く', '상상이 문을 연다'), topic.abstract, 'N3'),
  line('kanjou-wo-kakusazu-susume', '感情を隠さず進め', 'かんじょうをかくさずすすめ', 'kanjou wo kakusazu susume', text('Move forward without hiding your emotions', '不要隐藏感情继续前进', '感情を隠さず進め', '감정을 숨기지 말고 나아가'), topic.feeling, 'N3'),
  line('chishiki-wa-nakama-wo-mamoru-tate', '知識は仲間を守る盾だ', 'ちしきはなかまをまもるたてだ', 'chishiki wa nakama wo mamoru tate da', text('Knowledge is a shield that protects friends', '知识是守护伙伴的盾', '知識は仲間を守る盾だ', '지식은 동료를 지키는 방패야'), topic.friendship, 'N3'),
  line('hannou-yori-ippo-saki-e', '相手の反応より一歩先へ', 'あいてのはんのうよりいっぽさきへ', 'aite no hannou yori ippo saki e', text('Stay one step ahead of their reaction', '比对方的反应领先一步', '相手の反応より一歩先へ', '상대의 반응보다 한 걸음 앞서'), topic.growth, 'N3'),
  line('kanousei-wa-mada-nemutteiru', '可能性はまだ眠っている', 'かのうせいはまだねむっている', 'kanousei wa mada nemutte iru', text('Possibility is still sleeping', '可能性还在沉睡', '可能性はまだ眠っている', '가능성은 아직 잠들어 있어'), topic.mystery, 'N3'),
  line('joukyou-wo-kaeru-handan', '状況を変えるのは小さな判断だ', 'じょうきょうをかえるのはちいさなはんだんだ', 'joukyou wo kaeru no wa chiisana handan da', text('A small judgment can change the situation', '小小的判断可以改变局面', '状況を変えるのは小さな判断だ', '작은 판단이 상황을 바꿀 수 있어'), topic.society, 'N2'),
  line('sekinin-wo-seotte-mae-e', '責任を背負って前へ進む', 'せきにんをせおってまえへすすむ', 'sekinin wo seotte mae e susumu', text('I carry responsibility and move forward', '背负责任向前走', '責任を背負って前へ進む', '책임을 짊어지고 앞으로 나아가'), topic.courage, 'N2'),
  line('genjitsu-to-mukiau-yuuki', '現実と向き合う勇気がある', 'げんじつとむきあうゆうきがある', 'genjitsu to mukiau yuuki ga aru', text('I have the courage to face reality', '我有面对现实的勇气', '現実と向き合う勇気がある', '현실과 마주할 용기가 있어'), topic.courage, 'N2'),
  line('kachi-wa-dareka-ga-kimeru-mono-ja-nai', '価値は誰かが決めるものじゃない', 'かちはだれかがきめるものじゃない', 'kachi wa dareka ga kimeru mono ja nai', text('Value is not something others decide', '价值不是由别人决定的', '価値は誰かが決めるものじゃない', '가치는 남이 정하는 게 아니야'), topic.abstract, 'N2'),
  line('kadai-wo-koeta-saki-ni', '課題を越えた先に光がある', 'かだいをこえたさきにひかりがある', 'kadai wo koeta saki ni hikari ga aru', text('There is light beyond the task', '越过课题之后会有光', '課題を越えた先に光がある', '과제를 넘은 앞에 빛이 있어'), topic.growth, 'N2'),
  line('kimi-no-sentaku-ga-mirai-wo-sasaeru', '君の選択が未来を支える', 'きみのせんたくがみらいをささえる', 'kimi no sentaku ga mirai wo sasaeru', text('Your choice supports the future', '你的选择支撑着未来', '君の選択が未来を支える', '너의 선택이 미래를 지탱해'), topic.friendship, 'N2'),
  line('yakuwari-wa-jibun-de-tsukuru', '役割は自分で作るものだ', 'やくわりはじぶんでつくるものだ', 'yakuwari wa jibun de tsukuru mono da', text('A role is something you create yourself', '角色要由自己创造', '役割は自分で作るものだ', '역할은 스스로 만드는 거야'), topic.society, 'N2'),
  line('shoumei-wa-kokoro-ni-aru', '証明は心の奥にある', 'しょうめいはこころのおくにある', 'shoumei wa kokoro no oku ni aru', text('The proof is deep in the heart', '证明藏在内心深处', '証明は心の奥にある', '증명은 마음 깊은 곳에 있어'), topic.mystery, 'N2'),
  line('ishiki-ga-sekai-wo-kaeru', '意識が世界の見え方を変える', 'いしきがせかいのみえかたをかえる', 'ishiki ga sekai no miekata wo kaeru', text('Awareness changes how the world looks', '意识会改变看世界的方式', '意識が世界の見え方を変える', '의식이 세계를 보는 방식을 바꿔'), topic.abstract, 'N2'),
  line('shudan-yori-mamoritai-mono', '手段を選んででも守りたいものがある', 'しゅだんをえらんででもまもりたいものがある', 'shudan wo erande demo mamoritai mono ga aru', text('There is something I will protect at any cost', '有些东西无论如何都要守护', '手段を選んででも守りたいものがある', '무슨 수를 써서라도 지키고 싶은 것이 있어'), topic.courage, 'N2'),
  line('kanten-wo-kaereba-hikari', '観点を変えれば光が見える', 'かんてんをかえればひかりがみえる', 'kanten wo kaereba hikari ga mieru', text('Change the viewpoint and light appears', '改变观点就能看见光', '観点を変えれば光が見える', '관점을 바꾸면 빛이 보인다'), topic.abstract, 'N2'),
  line('kijun-wo-koete-idome', '限界を越えて挑め', 'げんかいをこえていどめ', 'genkai wo koete idome', text('Go beyond your limits and take the challenge', '超越极限去挑战', '限界を越えて挑め', '한계를 넘어 도전해'), topic.courage, 'N2'),
  line('jiritsu-shita-kokoro-de-sasaeau', '自立した心で支え合う', 'じりつしたこころでささえあう', 'jiritsu shita kokoro de sasaeau', text('Independent hearts support each other', '自立的心彼此支撑', '自立した心で支え合う', '자립한 마음으로 서로 지탱한다'), topic.friendship, 'N2'),
  line('katei-no-itami-mo-chikara', '過程の痛みも力になる', 'かていのいたみもちからになる', 'katei no itami mo chikara ni naru', text('Even the pain of the process becomes strength', '过程中的痛也会变成力量', '過程の痛みも力になる', '과정의 아픔도 힘이 된다'), topic.growth, 'N2'),
  line('keikou-wo-yonde-saki-e', '傾向を読んで先へ進む', 'けいこうをよんでさきへすすむ', 'keikou wo yonde saki e susumu', text('Read the tendency and move ahead', '读懂倾向后向前进', '傾向を読んで先へ進む', '경향을 읽고 앞으로 나아간다'), topic.mystery, 'N2'),
  line('michibiku-koe-wo-shinjiteiru', '導く声を信じている', 'みちびくこえをしんじている', 'michibiku koe wo shinjiteiru', text('I believe in the voice that guides me', '我相信引导我的声音', '導く声を信じている', '이끄는 목소리를 믿고 있어'), topic.friendship, 'N2'),
  line('kouzou-wo-yomeba-michi-ga-mieru', '構造を読めば道が見える', 'こうぞうをよめばみちがみえる', 'kouzou wo yomeba michi ga mieru', text('Read the structure and the path appears', '读懂结构就能看见道路', '構造を読めば道が見える', '구조를 읽으면 길이 보인다'), topic.abstract, 'N2'),
  line('shigen-wa-mirai-e-no-yakusoku', '資源は未来への約束だ', 'しげんはみらいへのやくそくだ', 'shigen wa mirai e no yakusoku da', text('Resources are a promise to the future', '资源是给未来的约定', '資源は未来への約束だ', '자원은 미래를 향한 약속이야'), topic.society, 'N2'),
  line('shuchou-wa-shizuka-na-honoo', '主張は静かな炎になる', 'しゅちょうはしずかなほのおになる', 'shuchou wa shizuka na honoo ni naru', text('A claim becomes a quiet flame', '主张会化作安静的火焰', '主張は静かな炎になる', '주장은 조용한 불꽃이 된다'), topic.courage, 'N2'),
  line('sonchou-ga-tsuyosa-wo-tsukuru', '尊重が強さを作る', 'そんちょうがつよさをつくる', 'sonchou ga tsuyosa wo tsukuru', text('Respect creates strength', '尊重会创造强大', '尊重が強さを作る', '존중이 강함을 만든다'), topic.society, 'N2'),
  line('iji-suru-yuuki-wo-wasurenai', '信念を貫く勇気を忘れない', 'しんねんをつらぬくゆうきをわすれない', 'shinnen wo tsuranuku yuuki wo wasurenai', text('Do not forget the courage to stay true to your convictions', '不要忘记贯彻信念的勇气', '信念を貫く勇気を忘れない', '신념을 관철할 용기를 잊지 않아'), topic.growth, 'N2'),
  line('suishin-suru-te-wo-hanasanai', '背中を押してくれた手を離さない', 'せなかをおしてくれたてをはなさない', 'senaka wo oshite kureta te wo hanasanai', text('I will not let go of the hand that pushes forward', '不会放开推进前行的手', '背中を押してくれた手を離さない', '앞으로 밀어 주는 손을 놓지 않아'), topic.friendship, 'N2'),
  line('hitei-no-saki-ni-mo-kotae', '否定の先にも答えがある', 'ひていのさきにもこたえがある', 'hitei no saki ni mo kotae ga aru', text('There is an answer beyond denial', '否定之后也有答案', '否定の先にも答えがある', '부정 너머에도 답이 있다'), topic.abstract, 'N2'),
  line('kouken-wa-namae-no-nai-hikari', '貢献は名前のない光だ', 'こうけんはなまえのないひかりだ', 'kouken wa namae no nai hikari da', text('Contribution is a nameless light', '贡献是无名之光', '貢献は名前のない光だ', '공헌은 이름 없는 빛이야'), topic.society, 'N2'),
  line('mujun-no-naka-ni-honshitsu', '矛盾の中にも本質は眠る', 'むじゅんのなかにもほんしつはねむる', 'mujun no naka ni mo honshitsu wa nemuru', text('Even in contradiction, essence sleeps', '矛盾之中也沉睡着本质', '矛盾の中にも本質は眠る', '모순 속에도 본질은 잠들어 있어'), topic.abstract, 'N1'),
  line('hakanai-yoin-wo-mune-ni', '儚い余韻を胸に進む', 'はかないよいんをむねにすすむ', 'hakanai yoin wo mune ni susumu', text('I move on with a fleeting afterglow in my heart', '怀着短暂的余韵继续前进', '儚い余韻を胸に進む', '덧없는 여운을 품고 나아가'), topic.nuance, 'N1'),
  line('kattou-goto-kakugo-ni-kaeru', '葛藤ごと覚悟に変える', 'かっとうごとかくごにかえる', 'kattou goto kakugo ni kaeru', text('I turn even conflict into resolve', '连同纠结一起化为觉悟', '葛藤ごと覚悟に変える', '갈등까지 각오로 바꿔'), topic.courage, 'N1'),
  line('bakuzen-to-shita-rinkaku', '漠然とした輪郭を見極める', 'ばくぜんとしたりんかくをみきわめる', 'bakuzen to shita rinkaku wo mikiwameru', text('I discern the vague outline', '看清模糊的轮廓', '漠然とした輪郭を見極める', '막연한 윤곽을 분별해'), topic.nuance, 'N1'),
  line('uketsuida-hikari-wo-tsuranuku', '受け継いだ光を貫く', 'うけついだひかりをつらぬく', 'uketsuida hikari wo tsuranuku', text('I carry through the light I inherited', '将继承的光贯彻到底', '受け継いだ光を貫く', '이어받은 빛을 끝까지 관철해'), topic.adventure, 'N1'),
  line('kaishaku-wo-kutsugaeshite', '解釈を覆して世界を見る', 'かいしゃくをくつがえしてせかいをみる', 'kaishaku wo kutsugaeshite sekai wo miru', text('I overturn interpretation and see the world anew', '推翻解读后重新看世界', '解釈を覆して世界を見る', '해석을 뒤집고 세계를 새롭게 봐'), topic.mystery, 'N1'),
  line('rinen-wa-yami-de-mo-yuraganai', '理念は闇の中でも揺らがない', 'りねんはやみのなかでもゆらがない', 'rinen wa yami no naka demo yuraganai', text('An ideal does not waver even in darkness', '理念即使在黑暗中也不动摇', '理念は闇の中でも揺らがない', '이념은 어둠 속에서도 흔들리지 않아'), topic.courage, 'N1'),
  line('muishiki-ga-sasayaku-namae', '無意識が名前を囁く', 'むいしきがなまえをささやく', 'muishiki ga namae wo sasayaku', text('The unconscious whispers a name', '无意识低语着一个名字', '無意識が名前を囁く', '무의식이 이름을 속삭여'), topic.mystery, 'N1'),
  line('shoudou-no-saki-ni-souzou', '衝動の先に創造がある', 'しょうどうのさきにそうぞうがある', 'shoudou no saki ni souzou ga aru', text('Creation waits beyond impulse', '冲动之后有创造', '衝動の先に創造がある', '충동 너머에 창조가 있어'), topic.abstract, 'N1'),
  line('tsukitometa-shinjitsu-wo-daite', '突き止めた真実を抱いて進む', 'つきとめたしんじつをだいてすすむ', 'tsukitometa shinjitsu wo daite susumu', text('I move forward holding the truth I tracked down', '怀抱查明的真相继续前进', '突き止めた真実を抱いて進む', '밝혀낸 진실을 품고 나아가'), topic.mystery, 'N1'),
  line('seijaku-no-naka-de-kyoumei', '静寂の中で共鳴する', 'せいじゃくのなかできょうめいする', 'seijaku no naka de kyoumei suru', text('Resonance blooms in silence', '在静寂中产生共鸣', '静寂の中で共鳴する', '정적 속에서 공명한다'), topic.nuance, 'N1'),
  line('bokyaku-no-saki-ni-zanzou', '忘却の先にも残像は消えない', 'ぼうきゃくのさきにもざんぞうはきえない', 'bokyaku no saki ni mo zanzou wa kienai', text('The afterimage does not fade beyond oblivion', '即使越过忘却，残像也不会消失', '忘却の先にも残像は消えない', '망각 너머에서도 잔상은 사라지지 않아'), topic.nuance, 'N1'),
  line('kyozou-wo-kudaite-kyoukai', '虚像を砕いて境界を越える', 'きょぞうをくだいてきょうかいをこえる', 'kyozou wo kudaite kyoukai wo koeru', text('Break the false image and cross the boundary', '击碎虚像越过边界', '虚像を砕いて境界を越える', '허상을 부수고 경계를 넘는다'), topic.mystery, 'N1'),
  line('keii-wo-daite-suii-wo-mimamoru', 'すべての経緯を知った上で、事態の推移を見守る', 'すべてのけいいをしったうえで、じたいのすいいをみまもる', 'subete no keii wo shitta ue de jitai no suii wo mimamoru', text('Knowing the whole story, I watch events unfold', '了解全部经过后，静观事态发展', 'すべての経緯を知った上で、事態の推移を見守る', '모든 경위를 안 뒤 사태의 추이를 지켜본다'), topic.abstract, 'N1'),
  line('honnou-ga-shoujou-wo-erabu', '本能が静かに象徴を選ぶ', 'ほんのうがしずかにしょうちょうをえらぶ', 'honnou ga shizuka ni shouchou wo erabu', text('Instinct quietly chooses a symbol', '本能安静地选择象征', '本能が静かに象徴を選ぶ', '본능이 조용히 상징을 고른다'), topic.nuance, 'N1'),
  line('shisaku-no-hate-de-henbou', '思索の果てで世界が変貌する', 'しさくのはてでせかいがへんぼうする', 'shisaku no hate de sekai ga henbou suru', text('At the end of contemplation, the world transforms', '思索尽头世界发生变貌', '思索の果てで世界が変貌する', '사색의 끝에서 세계가 변모한다'), topic.abstract, 'N1'),
  line('kiseki-wa-chinmoku-de-kagayaku', '軌跡は沈黙の中で輝く', 'きせきはちんもくのなかでかがやく', 'kiseki wa chinmoku no naka de kagayaku', text('The trajectory shines in silence', '轨迹在沉默中发光', '軌跡は沈黙の中で輝く', '궤적은 침묵 속에서 빛난다'), topic.nuance, 'N1'),
  line('goui-naki-yoru-wo-koete', '合意なき夜を越えて', 'ごういなきよるをこえて', 'goui naki yoru wo koete', text('Cross the night without consensus', '越过没有共识的夜晚', '合意なき夜を越えて', '합의 없는 밤을 넘어'), topic.society, 'N1'),
  line('anji-ga-unmei-wo-yurasu', '暗示が運命を揺らす', 'あんじがうんめいをゆらす', 'anji ga unmei wo yurasu', text('A hint shakes destiny', '暗示摇动命运', '暗示が運命を揺らす', '암시가 운명을 흔든다'), topic.mystery, 'N1'),
  line('keiki-wa-isshun-no-mabataki', '契機は一瞬のまばたき', 'けいきはいっしゅんのまばたき', 'keiki wa isshun no mabataki', text('A turning point is a single blink', '契机只是一瞬的眨眼', '契機は一瞬のまばたき', '계기는 한순간의 눈 깜빡임'), topic.growth, 'N1'),
  line('seiyaku-wo-bigaku-ni-kaeru', '制約を美学に変える', 'せいやくをびがくにかえる', 'seiyaku wo bigaku ni kaeru', text('Turn constraint into aesthetics', '把制约变成美学', '制約を美学に変える', '제약을 미학으로 바꾼다'), topic.abstract, 'N1'),
  line('taitou-suru-kage-wo-misueru', '台頭する影を見据える', 'たいとうするかげをみすえる', 'taitou suru kage wo misueru', text('Face the rising shadow', '凝视正在兴起的影子', '台頭する影を見据える', '대두하는 그림자를 똑바로 본다'), topic.mystery, 'N1'),
  line('teitai-no-soko-de-ishi-ga-moeru', '停滞の底で意志が燃える', 'ていたいのそこでいしがもえる', 'teitai no soko de ishi ga moeru', text('Will burns at the bottom of stagnation', '意志在停滞的底部燃烧', '停滞の底で意志が燃える', '정체의 바닥에서 의지가 불탄다'), topic.courage, 'N1'),
  line('ichiren-no-kioku-ga-kyoukai-wo-musubu', '一連の記憶が過去と未来を結ぶ', 'いちれんのきおくがかことみらいをむすぶ', 'ichiren no kioku ga kako to mirai wo musubu', text('A sequence of memories connects the past and future', '一连串记忆连接过去与未来', '一連の記憶が過去と未来を結ぶ', '일련의 기억이 과거와 미래를 잇는다'), topic.nuance, 'N1'),
  line('issho-ni-sora-wo-miyou', '一緒に空を見よう', 'いっしょにそらをみよう', 'issho ni sora wo miyou', text("Let's look at the sky together", '一起看天空吧', '一緒に空を見よう', '함께 하늘을 보자'), topic.friendship),
  line('chiisana-yume-wa-hajimaru', '小さな夢は始まる', 'ちいさなゆめははじまる', 'chiisana yume wa hajimaru', text('A small dream begins', '小小的梦想开始了', '小さな夢は始まる', '작은 꿈이 시작돼'), topic.adventure),
  line('yakusoku-no-saki-e-susumou', '約束の先へ進もう', 'やくそくのさきへすすもう', 'yakusoku no saki e susumou', text('Move beyond the promise', '越过约定继续前进', '約束の先へ進もう', '약속 너머로 나아가자'), topic.friendship, 'N4'),
  line('shizuka-na-yuuki-ga-todoku', '静かな勇気が届く', 'しずかなゆうきがとどく', 'shizuka na yuuki ga todoku', text('Quiet courage reaches someone', '安静的勇气会传达到某处', '静かな勇気が届く', '조용한 용기가 닿는다'), topic.courage, 'N4'),
  line('eranda-riyuu-wo-shinjite', '選んだ理由を信じて', 'えらんだりゆうをしんじて', 'eranda riyuu wo shinjite', text('Trust the reason you chose', '相信你选择的理由', '選んだ理由を信じて', '네가 선택한 이유를 믿어'), topic.growth, 'N3'),
  line('chiisana-keiken-ga-mirai-wo-kaeru', '小さな経験が未来を変える', 'ちいさなけいけんがみらいをかえる', 'chiisana keiken ga mirai wo kaeru', text('Small experiences change the future', '小小的经验会改变未来', '小さな経験が未来を変える', '작은 경험이 미래를 바꾼다'), topic.growth, 'N3'),
  line('shiten-wo-kaete-honshitsu-e', '視点を変えて本質へ進む', 'してんをかえてほんしつへすすむ', 'shiten wo kaete honshitsu e susumu', text('Change perspective and move toward essence', '改变视点向本质前进', '視点を変えて本質へ進む', '시점을 바꾸고 본질로 나아간다'), topic.abstract, 'N2'),
  line('sekinin-no-omosa-ga-hikari-ni-naru', '責任の重さが光になる', 'せきにんのおもさがひかりになる', 'sekinin no omosa ga hikari ni naru', text('The weight of responsibility becomes light', '责任的重量会化作光', '責任の重さが光になる', '책임의 무게가 빛이 된다'), topic.courage, 'N2'),
  line('yohaku-no-naka-de-shini-ga-yureru', '余白の中で真意が揺れる', 'よはくのなかでしんいがゆれる', 'yohaku no naka de shini ga yureru', text('True intent wavers in the blank space', '真意在留白中摇动', '余白の中で真意が揺れる', '진의가 여백 속에서 흔들린다'), topic.nuance, 'N1'),
  line('mujun-wo-daite-biishiki-e-itaru', '矛盾を抱いて美意識へ至る', 'むじゅんをだいてびいしきへいたる', 'mujun wo daite biishiki e itaru', text('Embrace contradiction and arrive at aesthetic sense', '怀抱矛盾抵达审美意识', '矛盾を抱いて美意識へ至る', '모순을 품고 미의식에 이른다'), topic.abstract, 'N1'),
];

export const KANA_ITEMS = [...HIRAGANA_ITEMS, ...KATAKANA_ITEMS];
export const MEANING_ITEMS = [...VOCAB_ITEMS, ...LINE_ITEMS];
export const ALL_ITEMS = [...KANA_ITEMS, ...MEANING_ITEMS, ...GRAMMAR_ITEMS];
export { GRAMMAR_ITEMS };

export function getLevelStudyStats(level: JlptLevel) {
  return {
    kana: level === 'N5' ? KANA_ITEMS.length : 0,
    vocab: VOCAB_ITEMS.filter((item) => item.level === level).length,
    lines: LINE_ITEMS.filter((item) => item.level === level).length,
    grammar: GRAMMAR_ITEMS.filter((item) => item.level === level).length,
  };
}

function vocab(
  id: string,
  display: string,
  kana: string,
  romaji: string,
  meaning: LocalizedText,
  itemTopic: LocalizedText,
  level: JlptLevel = 'N5',
): StudyItem {
  return {
    id: `vocab-${id}`,
    kind: 'vocab',
    level,
    display,
    kana,
    romaji,
    meaning,
    topic: itemTopic,
  };
}

function line(
  id: string,
  display: string,
  kana: string,
  romaji: string,
  meaning: LocalizedText,
  itemTopic: LocalizedText,
  level: JlptLevel = 'N5',
): StudyItem {
  return {
    id: `line-${id}`,
    kind: 'line',
    level,
    display,
    kana,
    romaji,
    meaning,
    topic: itemTopic,
  };
}

function text(en: string, zhHans: string, ja: string, ko: string): LocalizedText {
  return makeText(en, zhHans, ja, ko);
}
